# typed: true

require "herb"
require "prism"

require_relative "template_path"

module ErbCallSites
  # Transcribes the ViewComponent constructions in one ERB template into
  # plain Ruby, so that Sorbet can see call sites it otherwise treats as
  # string literals.
  #
  # Only the constructions are transcribed, not the template. Argument
  # values that reach outside the template -- view helpers, route helpers,
  # translations -- are replaced by `T.unsafe(nil)`, because reproducing
  # them would require a typed view context that does not exist yet. What
  # survives is enough for Sorbet to check keyword names, arity, the
  # component constant, and the types of literal arguments. See
  # docs/adr/0001-erb-call-site-typing.md for what that does and does
  # not catch.
  class Extractor
    COMPONENT_SUFFIX = "Component"
    private_constant :COMPONENT_SUFFIX

    UNTYPED = "T.unsafe(nil)"
    private_constant :UNTYPED

    sig { params(template: String, source_path: String).void }
    def initialize(template:, source_path:)
      @template = template
      @source_path = source_path
    end

    sig { returns(T::Boolean) }
    def call_sites? = call_sites.any?

    sig { returns(String) }
    def to_ruby
      <<~RUBY
        # typed: true

        # Generated by `bin/rake erb_call_sites:generate` from
        # #{source_path}. Do not edit by hand.

        module ErbCallSites
          class #{class_name}
            sig { void }
            def call
        #{indent(body, 6)}
            end
          end
        end
      RUBY
    end

    private

    attr_reader :template, :source_path

    sig { returns(String) }
    def body
      sections = [locals.join("\n"), *call_sites]

      sections.reject(&:empty?).join("\n\n")
    end

    sig { returns(String) }
    def class_name = TemplatePath.new(source_path).class_name

    # Every ERB tag in the template, paired with the line it starts on and
    # the Prism tree for its embedded Ruby. Tags whose Ruby does not stand
    # alone -- `if @x`, `do |x|` -- are closed with an `end` so that Prism
    # can parse them; tags that are only a closer are dropped.
    sig { returns(T::Array[T.untyped]) }
    def snippets
      @snippets ||= erb_nodes.filter_map do |node|
        source = node.content.value
        parsed = parse_standalone(source)
        {line: node.content.location.start.line, tree: parsed} if parsed
      end
    end

    sig { params(source: String).returns(T.untyped) }
    def parse_standalone(source)
      [source, "#{source}\nend"].each do |candidate|
        result = Prism.parse(candidate)
        return result.value if result.success?
      end

      nil
    end

    sig { returns(T::Array[T.untyped]) }
    def erb_nodes
      @erb_nodes ||= begin
        found = []
        collect_erb_nodes(Herb.parse(template).value, found)
        found
      end
    end

    sig { params(node: T.untyped, found: T::Array[T.untyped]).void }
    def collect_erb_nodes(node, found)
      return unless node.respond_to?(:child_nodes)

      node.child_nodes.compact.each do |child|
        if child.class.name.include?("ERB") && child.respond_to?(:content) &&
            child.content
          found << child
        end

        collect_erb_nodes(child, found)
      end
    end

    # One transcribed construction per entry, in template order, each
    # preceded by a comment naming where it came from.
    sig { returns(T::Array[String]) }
    def call_sites
      @call_sites ||= snippets.flat_map do |snippet|
        constructions(snippet.fetch(:tree)).map do |node|
          "# #{source_path}:#{snippet.fetch(:line)}\n#{transcribe(node)}"
        end
      end
    end

    # A construction counts when the class is named like a component, or
    # when it is what a `render` call was handed -- the second case is what
    # catches a misspelling, which loses the naming convention along with
    # the correct name.
    sig { params(tree: T.untyped).returns(T::Array[T.untyped]) }
    def constructions(tree)
      nodes = each_node(tree)
      rendered = nodes.flat_map { rendered_arguments(it) }

      nodes.select do |node|
        construction?(node) &&
          (component_name?(node) || rendered.include?(node))
      end
    end

    sig { params(node: T.untyped).returns(T::Array[T.untyped]) }
    def rendered_arguments(node)
      return [] unless node.is_a?(Prism::CallNode)
      return [] unless node.name == :render

      node.arguments&.arguments || []
    end

    sig { params(node: T.untyped).returns(T::Boolean) }
    def construction?(node)
      return false unless node.is_a?(Prism::CallNode)

      node.name == :new && !constant_name(node.receiver).nil?
    end

    sig { params(node: T.untyped).returns(T::Boolean) }
    def component_name?(node)
      constant_name(node.receiver)&.end_with?(COMPONENT_SUFFIX) || false
    end

    sig { params(node: T.untyped).returns(T.nilable(String)) }
    def constant_name(node)
      node.slice if node.is_a?(Prism::ConstantReadNode) ||
        node.is_a?(Prism::ConstantPathNode)
    end

    # Rebuilds `Foo::BarComponent.new(...)` from the parsed call, keeping
    # every keyword name and dropping only the values Sorbet could not
    # resolve outside a view.
    sig { params(node: T.untyped).returns(String) }
    def transcribe(node)
      "#{constant_name(node.receiver)}.new(#{transcribe_arguments(node)})"
    end

    sig { params(node: T.untyped).returns(String) }
    def transcribe_arguments(node)
      arguments = node.arguments&.arguments || []

      arguments.flat_map { |argument|
        if argument.is_a?(Prism::KeywordHashNode)
          argument.elements.map { transcribe_association(it) }
        else
          transcribe_value(argument)
        end
      }.join(", ")
    end

    sig { params(node: T.untyped).returns(String) }
    def transcribe_association(node)
      return transcribe_value(node) unless node.is_a?(Prism::AssocNode)

      # `task:` shorthand parses to an implicit value; name the local
      # explicitly so the generated Ruby stands alone.
      key = node.key.slice.delete_suffix(":")
      value = if node.value.is_a?(Prism::ImplicitNode)
        key
      else
        transcribe_value(node.value)
      end

      "#{key}: #{value}"
    end

    sig { params(node: T.untyped).returns(String) }
    def transcribe_value(node)
      resolvable?(node) ? node.slice : UNTYPED
    end

    # A value is kept verbatim when nothing in it calls a method the
    # generated file has no receiver for. Bare identifiers are fine --
    # they are declared as untyped locals -- but `t(".title")` or
    # `todo_room_path(@room)` are not.
    sig { params(node: T.untyped).returns(T::Boolean) }
    def resolvable?(node)
      ([node] + each_node(node)).none? { view_helper_call?(it) }
    end

    sig { params(node: T.untyped).returns(T::Boolean) }
    def view_helper_call?(node)
      return false unless node.is_a?(Prism::CallNode)
      return false unless node.receiver.nil?

      !bare_identifier?(node)
    end

    sig { params(node: T.untyped).returns(T::Boolean) }
    def bare_identifier?(node)
      return false unless node.is_a?(Prism::CallNode)

      node.receiver.nil? && node.arguments.nil? && node.block.nil? &&
        node.opening_loc.nil?
    end

    # Locals the transcribed constructions refer to: block parameters from
    # the template, partial locals, and anything else that reads as a bare
    # identifier. All untyped -- see the class comment.
    #
    # Read back out of the transcription rather than collected while
    # building it, so that only identifiers that actually survived into the
    # output are declared -- the ones inside a value replaced by
    # `T.unsafe(nil)` are gone and must not be.
    sig { returns(T::Array[String]) }
    def locals
      names = call_sites.flat_map { |site|
        each_node(Prism.parse(site).value)
          .select { bare_identifier?(it) }
          .map { it.name.to_s }
      }

      names.uniq.sort.map { "#{it} = #{UNTYPED}" }
    end

    sig { params(node: T.untyped).returns(T::Array[T.untyped]) }
    def each_node(node)
      return [] unless node.respond_to?(:compact_child_nodes)

      node.compact_child_nodes.flat_map { [it] + each_node(it) }
    end

    sig { params(source: String, width: Integer).returns(String) }
    def indent(source, width)
      source
        .lines
        .map { it.strip.empty? ? it : "#{" " * width}#{it}" }
        .join
    end
  end
end
