# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `archspec` gem.
# Please instead update this file by running `bin/tapioca gem archspec`.


# ArchSpec turns your application's architecture into executable checks.
#
# You describe components, dependencies, and boundaries in an +Archspec.rb+
# file written in the ArchSpec::DSL, then run <tt>archspec check</tt> to verify
# every change. ArchSpec indexes Ruby source with Rubydex, uses Prism for a
# handful of syntax-specific facts, and never boots the app.
#
# The DSL is the public API. An +Archspec.rb+ file is evaluated directly:
#
#   architecture :rails
#
#   component :services, in: "app/services/**/*.rb"
#   services.cannot_call :render, :redirect_to, receiver: :none
#
# See ArchSpec::DSL::Context for the top-level DSL and
# ArchSpec::DSL::ComponentProxy for per-component rules. See
# ArchSpec::Architectures for the bundled architecture presets.
#
# You can also build a definition in plain Ruby with ArchSpec.define.
#
# pkg:gem/archspec#lib/archspec/error.rb:3
module ArchSpec
  class << self
    # Builds an architecture definition from a block of DSL calls.
    #
    #   ArchSpec.define do
    #     component :models, in: "app/models/**/*.rb"
    #     component :controllers, in: "app/controllers/**/*.rb"
    #     models.cannot_use :controllers
    #   end
    #
    # An +Archspec.rb+ file is not written with this wrapper. Its top level is
    # already the DSL, so bare +component+ and +architecture+ calls work
    # directly. Use +define+ when constructing a definition from Ruby, such as
    # in a test.
    #
    # Returns the ArchSpec::Definition.
    #
    # pkg:gem/archspec#lib/archspec.rb:65
    def define(name = T.unsafe(nil), &block); end
  end
end

# pkg:gem/archspec#lib/archspec/model.rb:8
class ArchSpec::AnalysisDiagnostic < ::Data
  # pkg:gem/archspec#lib/archspec/model.rb:8
  def location; end

  # pkg:gem/archspec#lib/archspec/model.rb:8
  def message; end

  # pkg:gem/archspec#lib/archspec/model.rb:8
  def rule; end

  class << self
    # pkg:gem/archspec#lib/archspec/model.rb:8
    def [](*_arg0); end

    # pkg:gem/archspec#lib/archspec/model.rb:8
    def inspect; end

    # pkg:gem/archspec#lib/archspec/model.rb:8
    def members; end

    # pkg:gem/archspec#lib/archspec/model.rb:8
    def new(*_arg0); end
  end
end

# pkg:gem/archspec#lib/archspec/analyzer.rb:7
module ArchSpec::Analyzer
  extend ::ArchSpec::Analyzer

  # pkg:gem/archspec#lib/archspec/analyzer.rb:10
  def analyze(definition, root:); end

  private

  # pkg:gem/archspec#lib/archspec/analyzer.rb:50
  def ignored_files(definition, root); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:60
  def parse_errors_for(path, errors); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:36
  def ruby_files(definition, root); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:56
  def suppressions_for(comments); end
end

# pkg:gem/archspec#lib/archspec/analyzer.rb:66
module ArchSpec::Analyzer::SuppressionParser
  extend ::ArchSpec::Analyzer::SuppressionParser

  # pkg:gem/archspec#lib/archspec/analyzer.rb:72
  def parse(comments); end

  private

  # pkg:gem/archspec#lib/archspec/analyzer.rb:116
  def normalize_rule(rule); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:112
  def sorted_comments(comments); end
end

# pkg:gem/archspec#lib/archspec/analyzer.rb:69
ArchSpec::Analyzer::SuppressionParser::DISABLE_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/archspec#lib/archspec/analyzer.rb:70
ArchSpec::Analyzer::SuppressionParser::ENABLE_PATTERN = T.let(T.unsafe(nil), Regexp)

# Rubydex supplies the semantic graph. This pass records the few facts
# whose syntax matters to ArchSpec's rules or that Rubydex does not model.
#
# pkg:gem/archspec#lib/archspec/analyzer.rb:125
class ArchSpec::Analyzer::SyntaxOverlay
  # pkg:gem/archspec#lib/archspec/analyzer.rb:209
  def initialize; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:230
  def apply(graph, call_resolutions: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:207
  def call_sites; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:294
  def constant_name_at(path, location); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:207
  def constant_sites; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:269
  def declaration_kind(name, path); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:273
  def declaration_name(name, path = T.unsafe(nil), location = T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:306
  def method_owner(name, scope); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:299
  def method_owner_override(path, location); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:226
  def scan(path, node); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:290
  def superclass_fallback(name, path); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:286
  def superclass_override(name, path); end

  private

  # pkg:gem/archspec#lib/archspec/analyzer.rb:842
  def accessors_for(message, name); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:793
  def add_fallback_ancestry(graph, fallback); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:749
  def apply_generated_methods(graph); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:774
  def apply_method_fallbacks(graph); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:809
  def apply_mixin_fallbacks(graph); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:704
  def apply_visibility_modifier(path, owner, node, namespace, nesting, current, spec, default_scope, forced_method_owner); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:654
  def assigned_constant_name(node, namespace); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:660
  def builder_kind(value); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:684
  def builder_superclass(value); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:667
  def class_superclass(node); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:889
  def constant_arguments(node); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:949
  def constant_node?(node); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:940
  def constant_reference_name(node); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:953
  def contains?(outer, inner); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:860
  def current_attributes?(constant); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:852
  def generated_method_names(constant, node, message); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:923
  def instantiates_and_invokes(node); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:881
  def literal_require_argument(node); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:648
  def namespace_only_body?(body); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:962
  def normalize(name); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:958
  def position(line, column); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:895
  def prism_signatures(node); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:932
  def qualified_constant_name(node, namespace); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:915
  def receiver_kind(node); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:674
  def record_builder_superclass(name, path, value); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:616
  def record_constant_site(path, node, current_constant, nesting); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:735
  def record_generated_method(path, node, message, owner, location, visibility, scope); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:741
  def record_mixin_fallback(path, node, message, owner, location, nesting); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:640
  def record_namespace(name, path, namespace_only, declared_as:, location:); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:830
  def set_fallback_visibility(path, owner, names, scope, visibility); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:692
  def singleton_target(expression, current_constant); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:864
  def symbol_arguments(node); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:870
  def truthy_keyword_argument?(node, name); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:698
  def visibility_modifier(node); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:312
  def visit(path, node, current_constant: T.unsafe(nil), namespace: T.unsafe(nil), nesting: T.unsafe(nil), visibility: T.unsafe(nil), default_scope: T.unsafe(nil), forced_method_owner: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:555
  def visit_call(path, node, current_constant:, namespace:, nesting:, visibility:, default_scope:, forced_method_owner:); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:631
  def visit_children(path, node, current_constant:, namespace:, nesting:, visibility: T.unsafe(nil), default_scope: T.unsafe(nil), forced_method_owner: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:349
  def visit_class(path, node, current_constant:, namespace:, nesting:); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:416
  def visit_constant_assignment(path, node, current_constant:, namespace:, nesting:); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:482
  def visit_constant_body(path, name, body, namespace, nesting:, default_scope: T.unsafe(nil), forced_method_owner: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:513
  def visit_def(path, node, current_constant:, namespace:, nesting:, visibility:, default_scope:, forced_method_owner:); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:388
  def visit_module(path, node, current_constant:, namespace:, nesting:); end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:468
  def visit_singleton_class(path, node, current_constant:, namespace:, nesting:, visibility:, forced_method_owner:); end
end

# pkg:gem/archspec#lib/archspec/analyzer.rb:186
ArchSpec::Analyzer::SyntaxOverlay::BUILDER_KINDS = T.let(T.unsafe(nil), Hash)

# pkg:gem/archspec#lib/archspec/analyzer.rb:129
class ArchSpec::Analyzer::SyntaxOverlay::CallResolution < ::Data
  # pkg:gem/archspec#lib/archspec/analyzer.rb:129
  def receiver; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:129
  def scope; end

  class << self
    # pkg:gem/archspec#lib/archspec/analyzer.rb:129
    def [](*_arg0); end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:129
    def inspect; end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:129
    def members; end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:129
    def new(*_arg0); end
  end
end

# pkg:gem/archspec#lib/archspec/analyzer.rb:128
class ArchSpec::Analyzer::SyntaxOverlay::CallSite < ::Data
  # pkg:gem/archspec#lib/archspec/analyzer.rb:128
  def location; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:128
  def name; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:128
  def nesting; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:128
  def owner; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:128
  def path; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:128
  def receiver; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:128
  def receiver_name; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:128
  def scope; end

  class << self
    # pkg:gem/archspec#lib/archspec/analyzer.rb:128
    def [](*_arg0); end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:128
    def inspect; end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:128
    def members; end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:128
    def new(*_arg0); end
  end
end

# pkg:gem/archspec#lib/archspec/analyzer.rb:127
class ArchSpec::Analyzer::SyntaxOverlay::ConstantSite < ::Data
  # pkg:gem/archspec#lib/archspec/analyzer.rb:127
  def location; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:127
  def name; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:127
  def nesting; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:127
  def owner; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:127
  def path; end

  class << self
    # pkg:gem/archspec#lib/archspec/analyzer.rb:127
    def [](*_arg0); end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:127
    def inspect; end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:127
    def members; end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:127
    def new(*_arg0); end
  end
end

# pkg:gem/archspec#lib/archspec/analyzer.rb:146
ArchSpec::Analyzer::SyntaxOverlay::DYNAMIC_MESSAGES = T.let(T.unsafe(nil), Array)

# pkg:gem/archspec#lib/archspec/analyzer.rb:133
class ArchSpec::Analyzer::SyntaxOverlay::DeclarationFallback < ::Data
  # pkg:gem/archspec#lib/archspec/analyzer.rb:133
  def dynamic_superclass; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:133
  def kind; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:133
  def location; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:133
  def name; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:133
  def nesting; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:133
  def path; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:133
  def superclass; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:133
  def superclass_location; end

  class << self
    # pkg:gem/archspec#lib/archspec/analyzer.rb:133
    def [](*_arg0); end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:133
    def inspect; end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:133
    def members; end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:133
    def new(*_arg0); end
  end
end

# pkg:gem/archspec#lib/archspec/analyzer.rb:132
class ArchSpec::Analyzer::SyntaxOverlay::DeclarationName < ::Data
  # pkg:gem/archspec#lib/archspec/analyzer.rb:132
  def location; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:132
  def path; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:132
  def qualified; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:132
  def raw; end

  class << self
    # pkg:gem/archspec#lib/archspec/analyzer.rb:132
    def [](*_arg0); end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:132
    def inspect; end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:132
    def members; end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:132
    def new(*_arg0); end
  end
end

# pkg:gem/archspec#lib/archspec/analyzer.rb:158
ArchSpec::Analyzer::SyntaxOverlay::GENERATED_METHOD_MACROS = T.let(T.unsafe(nil), Hash)

# pkg:gem/archspec#lib/archspec/analyzer.rb:130
class ArchSpec::Analyzer::SyntaxOverlay::GeneratedMethod < ::Data
  # pkg:gem/archspec#lib/archspec/analyzer.rb:130
  def location; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:130
  def message; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:130
  def node; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:130
  def owner; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:130
  def path; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:130
  def scope; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:130
  def visibility; end

  class << self
    # pkg:gem/archspec#lib/archspec/analyzer.rb:130
    def [](*_arg0); end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:130
    def inspect; end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:130
    def members; end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:130
    def new(*_arg0); end
  end
end

# pkg:gem/archspec#lib/archspec/analyzer.rb:193
ArchSpec::Analyzer::SyntaxOverlay::MIXIN_EDGE_TYPES = T.let(T.unsafe(nil), Hash)

# pkg:gem/archspec#lib/archspec/analyzer.rb:143
class ArchSpec::Analyzer::SyntaxOverlay::MethodFallback < ::Data
  # pkg:gem/archspec#lib/archspec/analyzer.rb:143
  def location; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:143
  def name; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:143
  def owner; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:143
  def path; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:143
  def scope; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:143
  def signatures; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:143
  def visibility; end

  class << self
    # pkg:gem/archspec#lib/archspec/analyzer.rb:143
    def [](*_arg0); end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:143
    def inspect; end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:143
    def members; end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:143
    def new(*_arg0); end
  end
end

# pkg:gem/archspec#lib/archspec/analyzer.rb:131
class ArchSpec::Analyzer::SyntaxOverlay::MethodOwner < ::Data
  # pkg:gem/archspec#lib/archspec/analyzer.rb:131
  def location; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:131
  def owner; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:131
  def path; end

  class << self
    # pkg:gem/archspec#lib/archspec/analyzer.rb:131
    def [](*_arg0); end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:131
    def inspect; end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:131
    def members; end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:131
    def new(*_arg0); end
  end
end

# pkg:gem/archspec#lib/archspec/analyzer.rb:144
class ArchSpec::Analyzer::SyntaxOverlay::MixinFallback < ::Data
  # pkg:gem/archspec#lib/archspec/analyzer.rb:144
  def location; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:144
  def message; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:144
  def nesting; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:144
  def owner; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:144
  def path; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:144
  def target; end

  class << self
    # pkg:gem/archspec#lib/archspec/analyzer.rb:144
    def [](*_arg0); end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:144
    def inspect; end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:144
    def members; end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:144
    def new(*_arg0); end
  end
end

# pkg:gem/archspec#lib/archspec/analyzer.rb:126
class ArchSpec::Analyzer::SyntaxOverlay::Owner < ::Data
  # pkg:gem/archspec#lib/archspec/analyzer.rb:126
  def name; end

  # pkg:gem/archspec#lib/archspec/analyzer.rb:126
  def scope; end

  class << self
    # pkg:gem/archspec#lib/archspec/analyzer.rb:126
    def [](*_arg0); end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:126
    def inspect; end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:126
    def members; end

    # pkg:gem/archspec#lib/archspec/analyzer.rb:126
    def new(*_arg0); end
  end
end

# pkg:gem/archspec#lib/archspec/analyzer.rb:173
ArchSpec::Analyzer::SyntaxOverlay::SINGLE_NAME_MACROS = T.let(T.unsafe(nil), Array)

# pkg:gem/archspec#lib/archspec/analyzer.rb:184
ArchSpec::Analyzer::SyntaxOverlay::SINGULAR_ASSOCIATION_HELPERS = T.let(T.unsafe(nil), Array)

# pkg:gem/archspec#lib/archspec/analyzer.rb:183
ArchSpec::Analyzer::SyntaxOverlay::SINGULAR_ASSOCIATION_MACROS = T.let(T.unsafe(nil), Array)

# pkg:gem/archspec#lib/archspec/analyzer.rb:199
ArchSpec::Analyzer::SyntaxOverlay::VISIBILITY_MODIFIERS = T.let(T.unsafe(nil), Hash)

# Bundled architecture presets. Each applies a set of components and rules in
# one call, invoked from the DSL through
# ArchSpec::DSL::Context#architecture:
#
#   architecture :rails
#   architecture :layered, layers: { ... }
#
# Every preset accepts overrides for its directories, so you can keep the
# shape while pointing at your own paths. The presets are:
#
# - +:rails+: conventional MVC that keeps controller APIs out of models and
#   services. Options +components:+, +controller_api:+, +share_helpers:+.
# - +:rails_strict+: +:rails+ plus a cycle check and a concern independence
#   check. Adds option +concerns:+.
# - +:vanilla_rails+: +:rails+ plus empty-directory rules for the 37signals
#   style (forbidding +app/services+, +app/forms+, +app/policies+, and more)
#   and the concern independence check. Options +components:+, +empty:+,
#   +controller_api:+, +share_helpers:+, +concerns:+.
# - +:layered+: ordered layers that may only depend inward, with a cycle
#   check. Option +layers:+ (order matters).
# - +:hexagonal+: ports and adapters, keeping the domain away from adapters.
#   Options +application:+, +domain:+, +ports:+, +adapters:+.
# - +:clean+: clean architecture layers. Options +frameworks:+,
#   +interface_adapters:+, +use_cases:+, +entities:+.
# - +:modular_monolith+: named packages with per-package allowlists and
#   optional public APIs. Options +components:+ (required), +allow:+,
#   +public:+.
# - +:cqrs+: separates commands from queries and keeps writes out of queries.
#   Options +commands:+, +queries:+, +read_models:+, +mutating_methods:+.
# - +:event_driven+: events, publishers, and subscribers. Options +events:+,
#   +publishers:+, +subscribers:+.
# - +:ruby_conventions+: generic Ruby naming idioms (no +get_+/+set_+, no +is_+
#   prefix), applied project-wide. Adds no components, so it composes with any
#   other architecture. No options.
#
# See the {architecture guides}[https://archspecrb.dev/architectures/] for
# each preset in depth.
#
# pkg:gem/archspec#lib/archspec/architectures.rb:41
module ArchSpec::Architectures
  extend ::ArchSpec::Architectures

  # Applies the named preset to +dsl+, forwarding +options+ to it. Raises
  # ArchSpec::Error for an unknown name. Called by
  # ArchSpec::DSL::Context#architecture, so you rarely call it directly.
  #
  # pkg:gem/archspec#lib/archspec/architectures.rb:141
  def apply(name, dsl, **options); end

  # pkg:gem/archspec#lib/archspec/architectures.rb:215
  def clean(dsl, frameworks:, interface_adapters:, use_cases:, entities:); end

  # pkg:gem/archspec#lib/archspec/architectures.rb:244
  def cqrs(dsl, commands:, queries:, read_models:, mutating_methods:); end

  # pkg:gem/archspec#lib/archspec/architectures.rb:255
  def event_driven(dsl, events:, publishers:, subscribers:); end

  # pkg:gem/archspec#lib/archspec/architectures.rb:199
  def hexagonal(dsl, application:, domain:, ports:, adapters:); end

  # pkg:gem/archspec#lib/archspec/architectures.rb:186
  def layered(dsl, layers:); end

  # pkg:gem/archspec#lib/archspec/architectures.rb:227
  def modular_monolith(dsl, components:, allow: T.unsafe(nil), public: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/architectures.rb:150
  def rails(dsl, components:, controller_api:, share_helpers:); end

  # pkg:gem/archspec#lib/archspec/architectures.rb:169
  def rails_strict(dsl, components:, controller_api:, share_helpers:, concerns:); end

  # Applies the generic Ruby naming idioms project-wide: no +get_+/+set_+
  # accessors and no +is_+ predicate prefix. Adds no components, so it composes
  # with any other architecture. Project-specific conventions (the +with_x+ /
  # +without_x+ pairing, the +supports_*?+ ban) stay opt-in through the
  # +method_names.matching(...)+ primitives.
  #
  # pkg:gem/archspec#lib/archspec/architectures.rb:270
  def ruby_conventions(dsl); end

  # pkg:gem/archspec#lib/archspec/architectures.rb:176
  def vanilla_rails(dsl, components:, empty:, controller_api:, share_helpers:, concerns:); end

  private

  # pkg:gem/archspec#lib/archspec/architectures.rb:279
  def architecture_name(name); end

  # pkg:gem/archspec#lib/archspec/architectures.rb:316
  def define_component(dsl, name, selector); end

  # pkg:gem/archspec#lib/archspec/architectures.rb:310
  def define_components(dsl, components); end

  # pkg:gem/archspec#lib/archspec/architectures.rb:294
  def forbid_name(dsl, regex, reason, scope:); end

  # pkg:gem/archspec#lib/archspec/architectures.rb:336
  def independent_concerns(dsl, pattern); end

  # pkg:gem/archspec#lib/archspec/architectures.rb:306
  def normalize_map(map); end

  # pkg:gem/archspec#lib/archspec/architectures.rb:332
  def proxy_for(dsl, name); end

  # pkg:gem/archspec#lib/archspec/architectures.rb:285
  def validate_options!(name, defaults, options); end
end

# pkg:gem/archspec#lib/archspec/architectures.rb:96
ArchSpec::Architectures::CONTROLLER_METHODS = T.let(T.unsafe(nil), Array)

# Every option each architecture accepts, with its default. The single
# source of truth for #apply: option validation checks these keys, and the
# architecture methods receive these values merged with the caller's.
#
# pkg:gem/archspec#lib/archspec/architectures.rb:110
ArchSpec::Architectures::DEFAULTS = T.let(T.unsafe(nil), Hash)

# pkg:gem/archspec#lib/archspec/architectures.rb:66
ArchSpec::Architectures::DEFAULT_CLEAN = T.let(T.unsafe(nil), Hash)

# pkg:gem/archspec#lib/archspec/architectures.rb:94
ArchSpec::Architectures::DEFAULT_CONCERNS = T.let(T.unsafe(nil), String)

# pkg:gem/archspec#lib/archspec/architectures.rb:73
ArchSpec::Architectures::DEFAULT_CQRS = T.let(T.unsafe(nil), Hash)

# pkg:gem/archspec#lib/archspec/architectures.rb:79
ArchSpec::Architectures::DEFAULT_EVENT_DRIVEN = T.let(T.unsafe(nil), Hash)

# pkg:gem/archspec#lib/archspec/architectures.rb:59
ArchSpec::Architectures::DEFAULT_HEXAGONAL = T.let(T.unsafe(nil), Hash)

# pkg:gem/archspec#lib/archspec/architectures.rb:44
ArchSpec::Architectures::DEFAULT_LAYERED = T.let(T.unsafe(nil), Hash)

# pkg:gem/archspec#lib/archspec/architectures.rb:50
ArchSpec::Architectures::DEFAULT_RAILS_MVC = T.let(T.unsafe(nil), Hash)

# pkg:gem/archspec#lib/archspec/architectures.rb:97
ArchSpec::Architectures::MUTATING_METHODS = T.let(T.unsafe(nil), Array)

# pkg:gem/archspec#lib/archspec/architectures.rb:85
ArchSpec::Architectures::VANILLA_RAILS_EMPTY = T.let(T.unsafe(nil), Hash)

# The <tt>archspec</tt> command line. Backs the +exe/archspec+ executable and
# dispatches the +init+, +check+, +explain+, and +version+ subcommands.
#
#   archspec init
#   archspec check [PATHS...] [--config PATH] [--format text|json] [--update-todo]
#   archspec explain PATH_OR_CONSTANT
#
# #run returns the process exit status: 0 when clean, 1 when violations are
# found.
#
# pkg:gem/archspec#lib/archspec/cli.rb:15
module ArchSpec::CLI
  extend ::ArchSpec::CLI

  # pkg:gem/archspec#lib/archspec/cli.rb:26
  def run(argv, output: T.unsafe(nil), error: T.unsafe(nil)); end

  private

  # pkg:gem/archspec#lib/archspec/cli.rb:98
  def check(argv, output); end

  # pkg:gem/archspec#lib/archspec/cli.rb:150
  def explain(argv, output); end

  # pkg:gem/archspec#lib/archspec/cli.rb:213
  def formatter_for(name); end

  # pkg:gem/archspec#lib/archspec/cli.rb:58
  def help(argv, output); end

  # pkg:gem/archspec#lib/archspec/cli.rb:69
  def init(argv, output); end

  # pkg:gem/archspec#lib/archspec/cli.rb:174
  def load_definition(config_path); end

  # pkg:gem/archspec#lib/archspec/cli.rb:196
  def scope_to_paths(diagnostics, paths, root); end

  # pkg:gem/archspec#lib/archspec/cli.rb:207
  def todo_path_for(definition, root); end

  # pkg:gem/archspec#lib/archspec/cli.rb:224
  def usage(command = T.unsafe(nil)); end
end

# pkg:gem/archspec#lib/archspec/cli.rb:18
ArchSpec::CLI::CONFIG_FILE = T.let(T.unsafe(nil), String)

# pkg:gem/archspec#lib/archspec/cli.rb:20
ArchSpec::CLI::TEMPLATE = T.let(T.unsafe(nil), String)

# pkg:gem/archspec#lib/archspec/cli.rb:19
ArchSpec::CLI::USAGE_ERROR_STATUS = T.let(T.unsafe(nil), Integer)

# pkg:gem/archspec#lib/archspec/cli.rb:24
class ArchSpec::CLI::UsageError < ::ArchSpec::Error; end

# pkg:gem/archspec#lib/archspec/model.rb:162
class ArchSpec::Component
  # pkg:gem/archspec#lib/archspec/model.rb:165
  def initialize(name); end

  # pkg:gem/archspec#lib/archspec/model.rb:179
  def add_constant(name, path:, reason: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/model.rb:174
  def add_file(path, reason: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/model.rb:163
  def constant_reasons; end

  # pkg:gem/archspec#lib/archspec/model.rb:163
  def constants; end

  # pkg:gem/archspec#lib/archspec/model.rb:163
  def file_reasons; end

  # pkg:gem/archspec#lib/archspec/model.rb:163
  def files; end

  # pkg:gem/archspec#lib/archspec/model.rb:185
  def includes_constant?(name, path: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/model.rb:163
  def name; end
end

# How a component selects its members: by file glob, by namespace, or by
# explicit constant name. Created by ArchSpec::DSL::Context#component. The
# analyzer uses it to assign files and constants to the component.
#
# pkg:gem/archspec#lib/archspec/component_spec.rb:7
class ArchSpec::ComponentSpec
  # pkg:gem/archspec#lib/archspec/component_spec.rb:10
  def initialize(name, files: T.unsafe(nil), except: T.unsafe(nil), namespace: T.unsafe(nil), constants: T.unsafe(nil), descendants_of: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/component_spec.rb:8
  def ancestor_names; end

  # pkg:gem/archspec#lib/archspec/component_spec.rb:8
  def constants; end

  # pkg:gem/archspec#lib/archspec/component_spec.rb:8
  def exclude_patterns; end

  # pkg:gem/archspec#lib/archspec/component_spec.rb:8
  def file_patterns; end

  # pkg:gem/archspec#lib/archspec/component_spec.rb:28
  def matches_constant?(name); end

  # pkg:gem/archspec#lib/archspec/component_spec.rb:37
  def matching_ancestor(name, graph); end

  # pkg:gem/archspec#lib/archspec/component_spec.rb:19
  def merge!(other); end

  # pkg:gem/archspec#lib/archspec/component_spec.rb:8
  def name; end

  # pkg:gem/archspec#lib/archspec/component_spec.rb:8
  def namespaces; end

  private

  # pkg:gem/archspec#lib/archspec/component_spec.rb:46
  def normalize_constant(value); end
end

# pkg:gem/archspec#lib/archspec/model.rb:71
class ArchSpec::ConstantNode
  # pkg:gem/archspec#lib/archspec/model.rb:76
  def initialize(name:, kind:, path:, location:, nesting: T.unsafe(nil), namespace_only: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/model.rb:108
  def add_class_method(name, location:, visibility: T.unsafe(nil), signatures: T.unsafe(nil), alias_target: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/model.rb:101
  def add_instance_method(name, location:, visibility: T.unsafe(nil), signatures: T.unsafe(nil), alias_target: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/model.rb:115
  def add_mixin(kind, name); end

  # pkg:gem/archspec#lib/archspec/model.rb:93
  def class?; end

  # pkg:gem/archspec#lib/archspec/model.rb:72
  def class_methods; end

  # pkg:gem/archspec#lib/archspec/model.rb:72
  def instance_methods; end

  # pkg:gem/archspec#lib/archspec/model.rb:72
  def kind; end

  # pkg:gem/archspec#lib/archspec/model.rb:72
  def location; end

  # pkg:gem/archspec#lib/archspec/model.rb:72
  def method_definitions; end

  # pkg:gem/archspec#lib/archspec/model.rb:72
  def mixins; end

  # pkg:gem/archspec#lib/archspec/model.rb:97
  def module?; end

  # pkg:gem/archspec#lib/archspec/model.rb:72
  def name; end

  # pkg:gem/archspec#lib/archspec/model.rb:74
  def namespace_only; end

  # pkg:gem/archspec#lib/archspec/model.rb:74
  def namespace_only=(_arg0); end

  # pkg:gem/archspec#lib/archspec/model.rb:72
  def nesting; end

  # pkg:gem/archspec#lib/archspec/model.rb:72
  def path; end

  # Rewrites the visibility of already-recorded definitions, for the
  # <tt>private :foo, :bar</tt> form that names methods defined earlier.
  #
  # pkg:gem/archspec#lib/archspec/model.rb:121
  def set_visibility(name, scope, visibility); end

  # pkg:gem/archspec#lib/archspec/model.rb:74
  def superclass; end

  # pkg:gem/archspec#lib/archspec/model.rb:74
  def superclass=(_arg0); end
end

# The ArchSpec DSL.
#
# An +Archspec.rb+ file is evaluated in this context, so every method here is
# a top-level call in that file.
#
# pkg:gem/archspec#lib/archspec/dsl.rb:10
module ArchSpec::DSL
  class << self
    # Raises when any of +names+ is not a declared component. Shared by the
    # top-level DSL and the component proxies.
    #
    # pkg:gem/archspec#lib/archspec/dsl.rb:13
    def assert_known_components!(definition, names, for_rule:); end
  end
end

# A handle to one component, returned by ArchSpec::DSL::Context#component
# and by calling a declared component's name. Rule methods return +self+, so
# they chain.
#
#   services.cannot_use(:controllers).cannot_call(:render, receiver: :none)
#
# pkg:gem/archspec#lib/archspec/dsl.rb:169
class ArchSpec::DSL::ComponentProxy
  # pkg:gem/archspec#lib/archspec/dsl.rb:172
  def initialize(definition, name); end

  # Allowlists the components that may reference this one, the inverse of
  # #can_only_use. A reference from any other component fails. Use it to protect
  # a shared kernel or a component with a deliberately narrow audience.
  #
  #   shared_kernel.can_only_be_used_by :billing, :catalog
  #
  # Rule id: +dependencies.consumers+.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:209
  def can_only_be_used_by(*consumers, because: T.unsafe(nil)); end

  # Allowlists the components this one may depend on: only the listed
  # components are permitted, and a reference to any other declared
  # component fails. The mirror image of #can_only_be_used_by.
  #
  #   controllers.can_only_use :models, :services
  #
  # Rule id: +dependencies.allow+.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:184
  def can_only_use(*targets, because: T.unsafe(nil)); end

  # Forbids calling the named methods. By default any receiver matches, so
  # this catches +record.update+ and +cache.update+ alike. Pass
  # <tt>receiver: :none</tt> to match only bare, implicit-+self+ calls, or a
  # constant name to match that semantic class receiver and its descendants.
  #
  #   queries.cannot_call :save, :update, :destroy
  #   services.cannot_call :render, :params, receiver: :none
  #   models.cannot_call :find_by_sql, receiver: "ActiveRecord::Base"
  #
  # A bare call to a method the component defines, inherits, or generates
  # with +attr_*+, Rails +attribute+, or +delegate+ is treated as its own API
  # and not flagged. Resolved method aliases are matched to their target.
  # Rule id: +methods.forbid+.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:228
  def cannot_call(*methods, receiver: T.unsafe(nil), because: T.unsafe(nil)); end

  # Forbids defining the named methods in this component. Use it when the
  # method name itself is a design smell there, such as +call+ on a
  # component that should not hold command objects.
  #
  #   models.cannot_define :call
  #
  # Rule id: +methods.define_forbid+.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:240
  def cannot_define(*methods, because: T.unsafe(nil)); end

  # Forbids the one-shot <tt>Thing.new(...).call</tt> pattern, where a class
  # is instantiated and immediately invoked. Use it to steer a component
  # toward plain methods over anonymous command objects.
  #
  # Rule id: +objects.instantiate_and_invoke_forbid+.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:250
  def cannot_instantiate_and_invoke(because: T.unsafe(nil)); end

  # Forbids referencing the named constants or anything under them. Use this
  # when the boundary is a framework constant rather than a component.
  #
  #   models.cannot_reference_constants "ActionController", "ActionView"
  #
  # Rule id: +constants.forbid+.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:261
  def cannot_reference_constants(*constants, because: T.unsafe(nil)); end

  # Forbids a concern from referencing the constants that include it. A
  # concern that names its includer knows too much about who uses it, which
  # couples the two and defeats the point of extracting the concern.
  #
  #   component :model_concerns, in: "app/models/concerns/**/*.rb"
  #   model_concerns.cannot_reference_includers
  #
  # Rule id: +concerns.independence+.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:292
  def cannot_reference_includers(because: T.unsafe(nil)); end

  # Forbids depending on the named components. Narrower than #can_only_use:
  # only the listed components fail, other dependencies are left alone.
  #
  #   models.cannot_use :controllers, :helpers
  #
  # Rule id: +dependencies.forbid+.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:196
  def cannot_use(*targets, because: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/dsl.rb:170
  def definition; end

  # Starts a naming-convention rule over the component's defined, public
  # methods. Select the methods with +matching+, then assert something about
  # them. Every check is name-based and exact.
  #
  #   models.method_names.matching(/\A(get|set)_/).forbidden
  #   chat.method_names.matching(/\Awith_(?<base>.+)/).requires("without_%{base}")
  #   chat.method_names.matching(/\Awith_(?<b>.+)/).requires("%{b}", on: agent, scope: :class)
  #
  # Pass <tt>scope: :class</tt> to select class methods instead of instance
  # methods. See ArchSpec::Rules::Naming::Selected for the constraints
  # (+forbidden+, +requires+). Rule ids: +naming.forbidden+, +naming.requires+.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:362
  def method_names(scope: T.unsafe(nil)); end

  # Requires the component to hold no files. Use it to keep a directory
  # empty, such as +app/services+ in a vanilla Rails app, with a reason
  # shown in the diagnostic.
  #
  #   component(:services, in: "app/services/**/*.rb")
  #     .must_be_empty(because: "behavior belongs on models")
  #
  # Rule id: +components.empty+.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:305
  def must_be_empty(because: T.unsafe(nil)); end

  # Requires every class in the component to implement all the named
  # methods. Instance methods are checked by default; pass
  # <tt>scope: :class</tt> for the class side. Methods inherited from
  # resolvable superclasses or mixins count. Optional +arity:+ and
  # +keywords:+ constraints check whether each method accepts that call.
  #
  #   commands.must_implement :perform
  #   commands.must_implement :call, arity: 1, keywords: :actor
  #   jobs.must_implement :perform_later, scope: :class
  #
  # Rule id: +protocol.must_implement+.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:321
  def must_implement(*methods, scope: T.unsafe(nil), arity: T.unsafe(nil), keywords: T.unsafe(nil), because: T.unsafe(nil)); end

  # Requires every class in the component to implement at least one of the
  # named methods. Useful when a protocol allows either name. Pass
  # <tt>scope: :class</tt> to check the class side.
  #
  #   commands.must_implement_one_of :perform, :call
  #
  # Rule id: +protocol.must_implement_one_of+.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:346
  def must_implement_one_of(*methods, scope: T.unsafe(nil), because: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/dsl.rb:170
  def name; end

  # Marks part of the component as its public API. References from outside
  # must resolve to a public constant; everything else becomes private.
  #
  #   billing.public_api "packs/billing/app/public/**/*.rb"
  #   billing.public_api constants: "Billing::Api"
  #   billing.public_api namespace: "Billing::Public"
  #
  # +constants+ matches exact names, +namespace+ matches a name and its
  # children. Code inside the component may still reach its own internals.
  # Rule id: +dependencies.privacy+.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:276
  def public_api(*patterns, constants: T.unsafe(nil), namespace: T.unsafe(nil), because: T.unsafe(nil)); end

  private

  # pkg:gem/archspec#lib/archspec/dsl.rb:368
  def add_rule(rule, because: T.unsafe(nil)); end
end

# The top-level DSL. Declare the project, its components, an architecture
# preset, and global rules.
#
#   root "."
#   source "app/**/*.rb", "lib/**/*.rb"
#   ignore "app/legacy/**/*.rb"
#   todo "archspec_todo.yml"
#
#   component :models, in: "app/models/**/*.rb"
#   component :controllers, in: "app/controllers/**/*.rb"
#   models.cannot_use :controllers
#
# Declaring a component defines a reader for it, so +models+ and
# +controllers+ above return an ArchSpec::DSL::ComponentProxy you attach
# rules to.
#
# pkg:gem/archspec#lib/archspec/dsl.rb:36
module ArchSpec::DSL::Context
  # Applies a bundled architecture preset, defining its components and
  # rules together.
  #
  #   architecture :rails
  #   architecture :hexagonal
  #   architecture :modular_monolith, components: { ... }, allow: { ... }
  #
  # +preset+ is an alias. Use whichever word fits: +architecture+ reads well
  # for structural bundles like +:rails+, +preset+ for convention packs like
  # +:ruby_conventions+.
  #
  # See ArchSpec::Architectures for every preset and its options.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:128
  def architecture(name, **options); end

  # Declares a component: a named set of files, matched by glob, namespace,
  # explicit constant, or semantic ancestry.
  #
  #   component :services, in: "app/services/**/*.rb"
  #   component :workflows, in: "app/models/**/*.rb", except: "app/models/legacy/**/*.rb"
  #   component :billing, namespace: "Billing"
  #   component :legacy, constants: %w[OldReport OldExport]
  #   component :records, descendants_of: "ApplicationRecord"
  #
  # Returns an ArchSpec::DSL::ComponentProxy for attaching rules. The
  # component is also available by name later in the file.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:102
  def component(name, in: T.unsafe(nil), except: T.unsafe(nil), namespace: T.unsafe(nil), constants: T.unsafe(nil), descendants_of: T.unsafe(nil)); end

  # Yields each subdirectory matching a glob, so you can declare one
  # component per engine or pack without hardcoding their names. Paths
  # resolve against the +Archspec.rb+ directory, not the working directory,
  # so it does not matter where +archspec+ is run from.
  #
  #   each_directory "engines/*" do |name, path|
  #     component name, in: "#{path}/**/*.rb"
  #   end
  #
  # Yields the directory basename and its root-relative path. Returns the
  # <tt>[name, path]</tt> pairs when called without a block.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:80
  def each_directory(glob); end

  # Adds glob patterns for files to skip. Combines with the built-in
  # ignores for +.git+, +tmp+, +vendor+, and +node_modules+.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:54
  def ignore(*patterns); end

  # pkg:gem/archspec#lib/archspec/dsl.rb:153
  def method_missing(name, *_arg1, **_arg2, &_arg3); end

  # Forbids dependency cycles between components. Pass +among:+ to limit the
  # check to a subset; omit it to check every declared component.
  #
  #   no_cycles
  #   no_cycles among: %i[billing catalog shared]
  #
  # Rule id: +dependencies.no_cycles+.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:141
  def no_cycles(among: T.unsafe(nil), because: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/dsl.rb:132
  def preset(name, **options); end

  # Sets or reads the project root that file patterns resolve against.
  # Defaults to the directory of the +Archspec.rb+ file.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:39
  def root(path = T.unsafe(nil)); end

  # Adds a custom rule object. A rule responds to +id+ and
  # <tt>evaluate(graph)</tt>, returning ArchSpec::Diagnostic objects. Use
  # this to extend ArchSpec with project-specific checks.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:149
  def rule(rule, because: T.unsafe(nil)); end

  # Adds glob patterns for the files ArchSpec parses. Defaults cover
  # +app+, +lib+, packs, and engines. Component patterns are always
  # analyzed, so most projects never need this.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:48
  def source(*patterns); end

  # Points at a todo file of accepted violations. Diagnostics recorded there
  # are subtracted from future runs, so you can adopt ArchSpec in an existing
  # app without fixing everything first, then burn the list down.
  #
  #   todo "archspec_todo.yml"
  #
  # Write or refresh it with <tt>archspec check --update-todo</tt>.
  #
  # pkg:gem/archspec#lib/archspec/dsl.rb:65
  def todo(path = T.unsafe(nil)); end

  private

  # pkg:gem/archspec#lib/archspec/dsl.rb:159
  def respond_to_missing?(name, include_private = T.unsafe(nil)); end
end

# The result of evaluating an +Archspec.rb+ file: the project settings,
# declared components, and rules. ArchSpec::DSL::Context is mixed into an
# instance to provide the DSL, and the analyzer and evaluator read it to run
# the checks. Build one with ArchSpec.define.
#
# pkg:gem/archspec#lib/archspec/definition.rb:8
class ArchSpec::Definition
  # pkg:gem/archspec#lib/archspec/definition.rb:27
  def initialize(name = T.unsafe(nil)); end

  # The directory file patterns resolve against: root_path expanded from the
  # directory the Archspec.rb was loaded from (base_dir), or the working
  # directory when built without a file.
  #
  # pkg:gem/archspec#lib/archspec/definition.rb:65
  def absolute_root(base = T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/definition.rb:46
  def add_component(spec); end

  # pkg:gem/archspec#lib/archspec/definition.rb:42
  def add_ignore_patterns(patterns); end

  # pkg:gem/archspec#lib/archspec/definition.rb:58
  def add_rule(rule); end

  # pkg:gem/archspec#lib/archspec/definition.rb:38
  def add_source_patterns(patterns); end

  # pkg:gem/archspec#lib/archspec/definition.rb:69
  def analysis_patterns; end

  # pkg:gem/archspec#lib/archspec/definition.rb:24
  def base_dir; end

  # pkg:gem/archspec#lib/archspec/definition.rb:24
  def base_dir=(_arg0); end

  # pkg:gem/archspec#lib/archspec/definition.rb:54
  def component?(name); end

  # pkg:gem/archspec#lib/archspec/definition.rb:25
  def component_specs; end

  # pkg:gem/archspec#lib/archspec/definition.rb:25
  def ignore_patterns; end

  # pkg:gem/archspec#lib/archspec/definition.rb:24
  def name; end

  # pkg:gem/archspec#lib/archspec/definition.rb:24
  def name=(_arg0); end

  # pkg:gem/archspec#lib/archspec/definition.rb:24
  def root_path; end

  # pkg:gem/archspec#lib/archspec/definition.rb:24
  def root_path=(_arg0); end

  # pkg:gem/archspec#lib/archspec/definition.rb:25
  def rules; end

  # pkg:gem/archspec#lib/archspec/definition.rb:25
  def source_patterns; end

  # pkg:gem/archspec#lib/archspec/definition.rb:24
  def todo_path; end

  # pkg:gem/archspec#lib/archspec/definition.rb:24
  def todo_path=(_arg0); end
end

# pkg:gem/archspec#lib/archspec/definition.rb:16
ArchSpec::Definition::DEFAULT_IGNORE_PATTERNS = T.let(T.unsafe(nil), Array)

# pkg:gem/archspec#lib/archspec/definition.rb:9
ArchSpec::Definition::DEFAULT_SOURCE_PATTERNS = T.let(T.unsafe(nil), Array)

# One reported violation: the rule id, a message, the source location, the
# evidence ArchSpec found, and a confidence. Formatters and the todo file read
# these. Its #fingerprint is the stable id used to match todo entries and
# suppress specific findings.
#
# pkg:gem/archspec#lib/archspec/diagnostic.rb:10
class ArchSpec::Diagnostic
  # pkg:gem/archspec#lib/archspec/diagnostic.rb:13
  def initialize(rule:, message:, location:, evidence:, confidence: T.unsafe(nil), reason: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/diagnostic.rb:11
  def confidence; end

  # pkg:gem/archspec#lib/archspec/diagnostic.rb:11
  def evidence; end

  # Line numbers stay out of the fingerprint so todo entries survive edits
  # that only shift code around.
  #
  # pkg:gem/archspec#lib/archspec/diagnostic.rb:37
  def fingerprint(root: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/diagnostic.rb:11
  def location; end

  # pkg:gem/archspec#lib/archspec/diagnostic.rb:11
  def message; end

  # pkg:gem/archspec#lib/archspec/diagnostic.rb:11
  def reason; end

  # pkg:gem/archspec#lib/archspec/diagnostic.rb:11
  def rule; end

  # pkg:gem/archspec#lib/archspec/diagnostic.rb:45
  def to_h(root:); end

  # pkg:gem/archspec#lib/archspec/diagnostic.rb:22
  def with_reason(reason); end
end

# pkg:gem/archspec#lib/archspec/model.rb:129
class ArchSpec::Edge < ::Data
  # pkg:gem/archspec#lib/archspec/model.rb:129
  def confidence; end

  # pkg:gem/archspec#lib/archspec/model.rb:129
  def from_constant; end

  # pkg:gem/archspec#lib/archspec/model.rb:129
  def from_path; end

  # pkg:gem/archspec#lib/archspec/model.rb:129
  def lexical_nesting; end

  # pkg:gem/archspec#lib/archspec/model.rb:129
  def location; end

  # pkg:gem/archspec#lib/archspec/model.rb:129
  def receiver; end

  # pkg:gem/archspec#lib/archspec/model.rb:129
  def receiver_scope; end

  # pkg:gem/archspec#lib/archspec/model.rb:129
  def resolved_method; end

  # pkg:gem/archspec#lib/archspec/model.rb:129
  def resolved_receiver; end

  # pkg:gem/archspec#lib/archspec/model.rb:129
  def resolved_to; end

  # pkg:gem/archspec#lib/archspec/model.rb:129
  def to; end

  # pkg:gem/archspec#lib/archspec/model.rb:129
  def type; end

  # pkg:gem/archspec#lib/archspec/model.rb:157
  def verb; end

  class << self
    # pkg:gem/archspec#lib/archspec/model.rb:129
    def [](*_arg0); end

    # pkg:gem/archspec#lib/archspec/model.rb:129
    def inspect; end

    # pkg:gem/archspec#lib/archspec/model.rb:129
    def members; end

    # pkg:gem/archspec#lib/archspec/model.rb:129
    def new(*_arg0); end
  end
end

# Raised for configuration and usage errors, such as an unknown architecture
# name or a malformed rule option.
#
# pkg:gem/archspec#lib/archspec/error.rb:6
class ArchSpec::Error < ::StandardError; end

# pkg:gem/archspec#lib/archspec/evaluator.rb:4
module ArchSpec::Evaluator
  extend ::ArchSpec::Evaluator

  # pkg:gem/archspec#lib/archspec/evaluator.rb:7
  def evaluate(definition, graph, todo: T.unsafe(nil)); end

  private

  # pkg:gem/archspec#lib/archspec/evaluator.rb:23
  def parser_diagnostics(graph); end
end

# pkg:gem/archspec#lib/archspec/formatters/style.rb:4
module ArchSpec::Formatters; end

# Renders <tt>archspec explain</tt>: why a file or constant belongs to its
# components, and the facts ArchSpec found for it, in the same visual
# language as the check output. Raises ArchSpec::Error when the subject
# matches no file and no constant.
#
# pkg:gem/archspec#lib/archspec/formatters/explanation.rb:9
module ArchSpec::Formatters::Explanation
  private

  # pkg:gem/archspec#lib/archspec/formatters/explanation.rb:38
  def explain_constant(output, style, graph, subject); end

  # pkg:gem/archspec#lib/archspec/formatters/explanation.rb:23
  def explain_file(output, style, graph, path); end

  # Yields each label right-justified to the widest one, with the frame
  # gutter bar appended, so columns line up like the check output.
  #
  # pkg:gem/archspec#lib/archspec/formatters/explanation.rb:132
  def in_gutters(labels); end

  # pkg:gem/archspec#lib/archspec/formatters/explanation.rb:140
  def line_range(suppression); end

  # pkg:gem/archspec#lib/archspec/formatters/explanation.rb:12
  def print(output = T.unsafe(nil), graph:, subject:); end

  # pkg:gem/archspec#lib/archspec/formatters/explanation.rb:121
  def print_census(output, style, census); end

  # pkg:gem/archspec#lib/archspec/formatters/explanation.rb:73
  def print_component_reasons(output, style, assignments); end

  # pkg:gem/archspec#lib/archspec/formatters/explanation.rb:107
  def print_facts(output, style, facts, label:); end

  # pkg:gem/archspec#lib/archspec/formatters/explanation.rb:97
  def print_parse_errors(output, style, file); end

  # pkg:gem/archspec#lib/archspec/formatters/explanation.rb:85
  def print_suppressions(output, style, file); end

  class << self
    # pkg:gem/archspec#lib/archspec/formatters/explanation.rb:38
    def explain_constant(output, style, graph, subject); end

    # pkg:gem/archspec#lib/archspec/formatters/explanation.rb:23
    def explain_file(output, style, graph, path); end

    # Yields each label right-justified to the widest one, with the frame
    # gutter bar appended, so columns line up like the check output.
    #
    # pkg:gem/archspec#lib/archspec/formatters/explanation.rb:132
    def in_gutters(labels); end

    # pkg:gem/archspec#lib/archspec/formatters/explanation.rb:140
    def line_range(suppression); end

    # pkg:gem/archspec#lib/archspec/formatters/explanation.rb:12
    def print(output = T.unsafe(nil), graph:, subject:); end

    # pkg:gem/archspec#lib/archspec/formatters/explanation.rb:121
    def print_census(output, style, census); end

    # pkg:gem/archspec#lib/archspec/formatters/explanation.rb:73
    def print_component_reasons(output, style, assignments); end

    # pkg:gem/archspec#lib/archspec/formatters/explanation.rb:107
    def print_facts(output, style, facts, label:); end

    # pkg:gem/archspec#lib/archspec/formatters/explanation.rb:97
    def print_parse_errors(output, style, file); end

    # pkg:gem/archspec#lib/archspec/formatters/explanation.rb:85
    def print_suppressions(output, style, file); end
  end
end

# pkg:gem/archspec#lib/archspec/formatters/json.rb:7
module ArchSpec::Formatters::JSON
  private

  # pkg:gem/archspec#lib/archspec/formatters/json.rb:10
  def print(output = T.unsafe(nil), graph:, diagnostics:); end

  class << self
    # pkg:gem/archspec#lib/archspec/formatters/json.rb:10
    def print(output = T.unsafe(nil), graph:, diagnostics:); end
  end
end

# ANSI styling for terminal output, shared by the formatters. Enabled only
# when the output is a TTY and NO_COLOR is unset.
#
# pkg:gem/archspec#lib/archspec/formatters/style.rb:7
class ArchSpec::Formatters::Style
  # pkg:gem/archspec#lib/archspec/formatters/style.rb:8
  def initialize(output); end

  # pkg:gem/archspec#lib/archspec/formatters/style.rb:12
  def bold(text); end

  # pkg:gem/archspec#lib/archspec/formatters/style.rb:28
  def faint(text); end

  # pkg:gem/archspec#lib/archspec/formatters/style.rb:20
  def marker(text); end

  # pkg:gem/archspec#lib/archspec/formatters/style.rb:24
  def note(text); end

  # pkg:gem/archspec#lib/archspec/formatters/style.rb:16
  def severity(text); end

  private

  # pkg:gem/archspec#lib/archspec/formatters/style.rb:34
  def paint(text, code); end
end

# Prints diagnostics the way clang and herb do: a severity header with the
# rule id, the location, a code frame with the offending span underlined,
# and the evidence as a note.
#
#   [error] models must not depend on controllers [dependencies.forbid]
#
#   app/models/user.rb:3:3
#
#       2 │ class User
#     → 3 │   UsersController
#         │   ^~~~~~~~~~~~~~~
#       4 │ end
#
#     note: User references UsersController
#
# Output to a terminal is colored; a non-TTY or a NO_COLOR environment
# disables the colors.
#
# pkg:gem/archspec#lib/archspec/formatters/text.rb:22
module ArchSpec::Formatters::Text
  private

  # The evidence as a note, or nil when it would only repeat the location
  # shown above it, as parse-error evidence does.
  #
  # pkg:gem/archspec#lib/archspec/formatters/text.rb:87
  def note_for(diagnostic, relative); end

  # pkg:gem/archspec#lib/archspec/formatters/text.rb:27
  def print(output = T.unsafe(nil), graph:, diagnostics:); end

  # pkg:gem/archspec#lib/archspec/formatters/text.rb:115
  def print_census(output, graph); end

  # pkg:gem/archspec#lib/archspec/formatters/text.rb:47
  def print_diagnostic(output, style, graph, diagnostic, sources); end

  # pkg:gem/archspec#lib/archspec/formatters/text.rb:65
  def print_frame(output, style, location, lines); end

  # pkg:gem/archspec#lib/archspec/formatters/text.rb:107
  def read_lines(path); end

  # pkg:gem/archspec#lib/archspec/formatters/text.rb:95
  def underline(location, text); end

  class << self
    # The evidence as a note, or nil when it would only repeat the location
    # shown above it, as parse-error evidence does.
    #
    # pkg:gem/archspec#lib/archspec/formatters/text.rb:87
    def note_for(diagnostic, relative); end

    # pkg:gem/archspec#lib/archspec/formatters/text.rb:27
    def print(output = T.unsafe(nil), graph:, diagnostics:); end

    # pkg:gem/archspec#lib/archspec/formatters/text.rb:115
    def print_census(output, graph); end

    # pkg:gem/archspec#lib/archspec/formatters/text.rb:47
    def print_diagnostic(output, style, graph, diagnostic, sources); end

    # pkg:gem/archspec#lib/archspec/formatters/text.rb:65
    def print_frame(output, style, location, lines); end

    # pkg:gem/archspec#lib/archspec/formatters/text.rb:107
    def read_lines(path); end

    # pkg:gem/archspec#lib/archspec/formatters/text.rb:95
    def underline(location, text); end
  end
end

# pkg:gem/archspec#lib/archspec/formatters/text.rb:23
ArchSpec::Formatters::Text::CONTEXT_LINES = T.let(T.unsafe(nil), Integer)

# pkg:gem/archspec#lib/archspec/model.rb:192
class ArchSpec::Graph
  # pkg:gem/archspec#lib/archspec/model.rb:205
  def initialize(root); end

  # pkg:gem/archspec#lib/archspec/model.rb:261
  def add_analysis_diagnostic(rule:, message:, location:); end

  # pkg:gem/archspec#lib/archspec/model.rb:226
  def add_constant(name:, kind:, path:, location:, nesting: T.unsafe(nil), namespace_only: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/model.rb:241
  def add_edge(type:, from_path:, from_constant:, to:, location:, confidence: T.unsafe(nil), receiver: T.unsafe(nil), lexical_nesting: T.unsafe(nil), resolved_to: T.unsafe(nil), resolved_receiver: T.unsafe(nil), receiver_scope: T.unsafe(nil), resolved_method: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/model.rb:217
  def add_file(path:, parse_errors:, suppressions: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/model.rb:507
  def analysis_census(path: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/model.rb:203
  def analysis_diagnostics; end

  # Every resolvable ancestor in Ruby lookup order, plus names whose
  # declarations are outside the analyzed source. The scope controls whether
  # mixins come from include/prepend or extend; superclass traversal applies
  # to both sides.
  #
  # pkg:gem/archspec#lib/archspec/model.rb:403
  def ancestor_names(name, scope: T.unsafe(nil), visited: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/model.rb:293
  def assign_components(component_specs); end

  # pkg:gem/archspec#lib/archspec/model.rb:535
  def component_assignment_reasons_for_constant(name, path: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/model.rb:527
  def component_assignment_reasons_for_path(path); end

  # pkg:gem/archspec#lib/archspec/model.rb:341
  def component_names_for_constant(name, path: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/model.rb:335
  def component_names_for_path(path); end

  # pkg:gem/archspec#lib/archspec/model.rb:203
  def components; end

  # pkg:gem/archspec#lib/archspec/model.rb:203
  def constants; end

  # pkg:gem/archspec#lib/archspec/model.rb:545
  def constants_for_component(name); end

  # pkg:gem/archspec#lib/archspec/model.rb:276
  def constants_for_path(path); end

  # pkg:gem/archspec#lib/archspec/model.rb:272
  def constants_named(name); end

  # pkg:gem/archspec#lib/archspec/model.rb:366
  def dependency_edges; end

  # The edge's source as prose: its constant when known, otherwise the
  # root-relative path of the file. Diagnostics use this so evidence never
  # embeds an absolute path, which would make todo fingerprints
  # machine-specific.
  #
  # pkg:gem/archspec#lib/archspec/model.rb:353
  def edge_source_name(edge); end

  # pkg:gem/archspec#lib/archspec/model.rb:203
  def edges; end

  # pkg:gem/archspec#lib/archspec/model.rb:439
  def effective_class_methods(name); end

  # pkg:gem/archspec#lib/archspec/model.rb:435
  def effective_instance_methods(name); end

  # Method definitions visible on a constant, including resolvable ancestry.
  # Extended modules contribute their instance methods to the class side.
  #
  # pkg:gem/archspec#lib/archspec/model.rb:445
  def effective_method_definitions(name, scope, visited = T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/model.rb:494
  def effective_methods(name, scope); end

  # pkg:gem/archspec#lib/archspec/model.rb:203
  def files; end

  # pkg:gem/archspec#lib/archspec/model.rb:502
  def incoming_dependency_edges(name); end

  # Every method definition in the graph, across all constants. Used by
  # project-wide naming rules that are not scoped to one component.
  #
  # pkg:gem/archspec#lib/archspec/model.rb:289
  def method_definitions; end

  # pkg:gem/archspec#lib/archspec/model.rb:280
  def method_definitions_for_component(name); end

  # pkg:gem/archspec#lib/archspec/model.rb:379
  def resolve_constant_reference(name, from_constant = T.unsafe(nil), lexical_nesting: T.unsafe(nil)); end

  # Resolves an edge with the lexical nesting captured where the reference
  # appeared. This matters for compact class declarations and superclass
  # expressions, where inferring scope from the finished class name is wrong.
  #
  # pkg:gem/archspec#lib/archspec/model.rb:393
  def resolve_edge_constant(edge); end

  # pkg:gem/archspec#lib/archspec/model.rb:480
  def resolve_method_alias(owner, name, scope, visited = T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/model.rb:203
  def root; end

  # pkg:gem/archspec#lib/archspec/model.rb:265
  def set_namespace_only(name, path, value); end

  # Components that own the source of an edge. Constant and namespace
  # selectors stay precise when a file also defines unrelated constants;
  # top-level edges fall back to the file assignment.
  #
  # pkg:gem/archspec#lib/archspec/model.rb:360
  def source_components_for(edge); end

  # pkg:gem/archspec#lib/archspec/model.rb:552
  def suppressed?(diagnostic); end

  # pkg:gem/archspec#lib/archspec/model.rb:370
  def target_components_for(edge); end

  private

  # pkg:gem/archspec#lib/archspec/model.rb:558
  def append_mixin_definitions(nodes, kind, definitions, visible_names, unresolved, visited); end

  # pkg:gem/archspec#lib/archspec/model.rb:575
  def append_superclass_definitions(nodes, scope, definitions, visible_names, unresolved, visited); end

  # pkg:gem/archspec#lib/archspec/model.rb:585
  def append_visible_definitions(definitions, visible_names, candidates); end

  # pkg:gem/archspec#lib/archspec/model.rb:591
  def defers_to_real_definition?(constant); end

  # pkg:gem/archspec#lib/archspec/model.rb:596
  def each_matching_file(pattern); end

  # pkg:gem/archspec#lib/archspec/model.rb:608
  def inferred_nesting(from_constant); end

  # pkg:gem/archspec#lib/archspec/model.rb:604
  def normalize_constant(value); end
end

# pkg:gem/archspec#lib/archspec/model.rb:193
ArchSpec::Graph::DEPENDENCY_EDGE_TYPES = T.let(T.unsafe(nil), Array)

# pkg:gem/archspec#lib/archspec/model.rb:201
ArchSpec::Graph::RESOLVED_ROOTS = T.let(T.unsafe(nil), Array)

# pkg:gem/archspec#lib/archspec/model.rb:50
class ArchSpec::MethodDefinition < ::Data
  # pkg:gem/archspec#lib/archspec/model.rb:50
  def alias_target; end

  # pkg:gem/archspec#lib/archspec/model.rb:50
  def location; end

  # pkg:gem/archspec#lib/archspec/model.rb:50
  def name; end

  # pkg:gem/archspec#lib/archspec/model.rb:50
  def owner; end

  # pkg:gem/archspec#lib/archspec/model.rb:50
  def scope; end

  # pkg:gem/archspec#lib/archspec/model.rb:50
  def signatures; end

  # pkg:gem/archspec#lib/archspec/model.rb:50
  def visibility; end

  class << self
    # pkg:gem/archspec#lib/archspec/model.rb:50
    def [](*_arg0); end

    # pkg:gem/archspec#lib/archspec/model.rb:50
    def inspect; end

    # pkg:gem/archspec#lib/archspec/model.rb:50
    def members; end

    # pkg:gem/archspec#lib/archspec/model.rb:50
    def new(*_arg0); end
  end
end

# pkg:gem/archspec#lib/archspec/model.rb:9
class ArchSpec::MethodSignature < ::Data
  # pkg:gem/archspec#lib/archspec/model.rb:19
  def accepts_arity?(arity); end

  # pkg:gem/archspec#lib/archspec/model.rb:26
  def accepts_keywords?(names); end

  # pkg:gem/archspec#lib/archspec/model.rb:9
  def block; end

  # pkg:gem/archspec#lib/archspec/model.rb:36
  def describe; end

  # pkg:gem/archspec#lib/archspec/model.rb:9
  def forward; end

  # pkg:gem/archspec#lib/archspec/model.rb:9
  def keyword_rest; end

  # pkg:gem/archspec#lib/archspec/model.rb:9
  def keywords; end

  # pkg:gem/archspec#lib/archspec/model.rb:9
  def optional; end

  # pkg:gem/archspec#lib/archspec/model.rb:9
  def optional_keywords; end

  # pkg:gem/archspec#lib/archspec/model.rb:9
  def required; end

  # pkg:gem/archspec#lib/archspec/model.rb:9
  def rest; end

  class << self
    # pkg:gem/archspec#lib/archspec/model.rb:9
    def [](*_arg0); end

    # pkg:gem/archspec#lib/archspec/model.rb:9
    def inspect; end

    # pkg:gem/archspec#lib/archspec/model.rb:9
    def members; end

    # pkg:gem/archspec#lib/archspec/model.rb:9
    def new(*_arg0); end
  end
end

# pkg:gem/archspec#lib/archspec/model.rb:7
class ArchSpec::ParseError < ::Data
  # pkg:gem/archspec#lib/archspec/model.rb:7
  def location; end

  # pkg:gem/archspec#lib/archspec/model.rb:7
  def message; end

  class << self
    # pkg:gem/archspec#lib/archspec/model.rb:7
    def [](*_arg0); end

    # pkg:gem/archspec#lib/archspec/model.rb:7
    def inspect; end

    # pkg:gem/archspec#lib/archspec/model.rb:7
    def members; end

    # pkg:gem/archspec#lib/archspec/model.rb:7
    def new(*_arg0); end
  end
end

# Translates Rubydex's semantic index into the small graph ArchSpec's rules
# consume. Rubydex owns Ruby semantics here: declarations, constant
# resolution, ancestry and methods all come from its resolved graph. The
# Prism pass in Analyzer adds only syntax facts Rubydex does not expose.
#
# pkg:gem/archspec#lib/archspec/rubydex_index.rb:14
class ArchSpec::RubydexIndex
  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:17
  def initialize(paths, syntax:, method_names: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:15
  def call_resolutions; end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:24
  def populate(graph); end

  private

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:99
  def add_ancestry(graph); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:141
  def add_ancestry_edge(graph, type, name, definition, reference, target, resolved); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:154
  def add_constant_references(graph); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:45
  def add_constants(graph); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:290
  def add_diagnostics(graph); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:66
  def add_methods(graph); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:327
  def attached(declaration); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:357
  def canonical_name(name); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:43
  def configured_method_names; end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:353
  def declarations; end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:171
  def declarations_with_workspace_definitions; end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:203
  def kind_of(declaration); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:249
  def method_alias_target(definition); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:223
  def method_names(declaration, definition); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:211
  def method_owner(declaration, definition, path); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:315
  def mixin_kind(mixin); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:331
  def nesting_of(definition, path); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:373
  def path_of(location); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:43
  def paths; end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:303
  def reference_target(reference, path); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:272
  def relevant_call_names; end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:255
  def resolve_call_sites; end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:339
  def semantic_name(declaration, path = T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:232
  def signatures_for(definition); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:363
  def source_location(path, location); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:43
  def syntax; end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:323
  def visibility_of(declaration); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:345
  def workspace_definition_path(declaration); end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:185
  def workspace_method_definitions; end

  # pkg:gem/archspec#lib/archspec/rubydex_index.rb:196
  def workspace_namespaces; end
end

# The checks ArchSpec runs. Each rule responds to +id+ (its stable rule id,
# used in suppressions and the todo file) and <tt>evaluate(graph)</tt>, which
# returns ArchSpec::Diagnostic objects. You normally add rules through the
# ArchSpec::DSL rather than instantiating these directly, but you can pass a
# custom object of the same shape to ArchSpec::DSL::Context#rule.
#
# pkg:gem/archspec#lib/archspec/rules/reasoned.rb:4
module ArchSpec::Rules
  private

  # pkg:gem/archspec#lib/archspec/rules/reasoned.rb:29
  def with_reason(rule, because); end

  class << self
    # pkg:gem/archspec#lib/archspec/rules/reasoned.rb:29
    def with_reason(rule, because); end
  end
end

# Backs ArchSpec::DSL::ComponentProxy#can_only_use. Flags references from the
# source to any component outside its allowlist.
#
# pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:38
class ArchSpec::Rules::AllowDependenciesRule < ::ArchSpec::Rules::DependencyRule
  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:43
  def evaluate(graph); end

  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:39
  def id; end
end

# Backs ArchSpec::DSL::ComponentProxy#can_only_be_used_by. The inverse of an
# allowlist: flags references to the component from any component that is not
# an approved consumer. Use it to protect a shared kernel.
#
# pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:85
class ArchSpec::Rules::AllowedConsumersRule
  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:88
  def initialize(source, consumers); end

  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:86
  def consumers; end

  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:106
  def evaluate(graph); end

  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:102
  def id; end

  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:97
  def merge!(other); end

  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:93
  def merge_key; end

  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:86
  def source; end

  private

  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:127
  def message_for(offender); end
end

# Backs ArchSpec::DSL::ComponentProxy#cannot_call. Flags calls to the named
# methods, optionally only bare implicit-+self+ calls.
#
# pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:7
class ArchSpec::Rules::CannotCallRule
  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:10
  def initialize(source, methods, receiver: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:33
  def evaluate(graph); end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:29
  def id; end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:24
  def merge!(other); end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:20
  def merge_key; end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:8
  def method_names; end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:8
  def receiver; end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:8
  def source; end

  private

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:66
  def evidence_for(graph, edge); end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:54
  def forbidden_name(edge); end

  # A receiverless call to a method the class itself defines (directly,
  # inherited, or via attr_*/attribute/delegate) is a call to its own API.
  #
  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:74
  def own_method_call?(graph, edge); end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:59
  def receiver_matches?(graph, edge); end
end

# Backs ArchSpec::DSL::ComponentProxy#cannot_define. Flags method
# definitions in the component matching the named methods.
#
# pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:268
class ArchSpec::Rules::CannotDefineMethodRule
  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:271
  def initialize(source, methods); end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:289
  def evaluate(graph); end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:285
  def id; end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:280
  def merge!(other); end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:276
  def merge_key; end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:269
  def method_names; end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:269
  def source; end
end

# Backs ArchSpec::DSL::ComponentProxy#cannot_instantiate_and_invoke. Flags
# the one-shot <tt>Thing.new(...).call</tt> pattern.
#
# pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:305
class ArchSpec::Rules::CannotInstantiateAndInvokeRule
  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:308
  def initialize(source); end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:320
  def evaluate(graph); end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:316
  def id; end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:312
  def merge_key; end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:306
  def source; end
end

# Backs ArchSpec::DSL::ComponentProxy#cannot_reference_constants. Flags
# references to the named constants or anything nested under them.
#
# pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:136
class ArchSpec::Rules::CannotReferenceConstantsRule
  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:139
  def initialize(source, constants); end

  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:137
  def constants; end

  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:157
  def evaluate(graph); end

  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:153
  def id; end

  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:148
  def merge!(other); end

  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:144
  def merge_key; end

  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:137
  def source; end
end

# Backs ArchSpec::DSL::ComponentProxy#cannot_reference_includers. A concern
# is a module mixed into other classes; this flags a concern that names the
# very constant that includes it, which is a circular knowledge dependency.
#
# pkg:gem/archspec#lib/archspec/rules/concern_rules.rb:8
class ArchSpec::Rules::ConcernIndependenceRule
  # pkg:gem/archspec#lib/archspec/rules/concern_rules.rb:13
  def initialize(source); end

  # pkg:gem/archspec#lib/archspec/rules/concern_rules.rb:25
  def evaluate(graph); end

  # pkg:gem/archspec#lib/archspec/rules/concern_rules.rb:21
  def id; end

  # pkg:gem/archspec#lib/archspec/rules/concern_rules.rb:17
  def merge_key; end

  # pkg:gem/archspec#lib/archspec/rules/concern_rules.rb:11
  def source; end

  private

  # Maps each mixed-in module to the set of constants that mix it in.
  #
  # pkg:gem/archspec#lib/archspec/rules/concern_rules.rb:59
  def includers_by_module(graph); end

  # pkg:gem/archspec#lib/archspec/rules/concern_rules.rb:54
  def within_namespace?(constant, namespace); end
end

# pkg:gem/archspec#lib/archspec/rules/concern_rules.rb:9
ArchSpec::Rules::ConcernIndependenceRule::MIXIN_TYPES = T.let(T.unsafe(nil), Array)

# Base for the allow and forbid dependency rules. Merges repeated
# declarations for the same source component.
#
# pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:12
class ArchSpec::Rules::DependencyRule
  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:15
  def initialize(source, targets); end

  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:24
  def merge!(other); end

  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:20
  def merge_key; end

  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:13
  def source; end

  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:13
  def targets; end

  private

  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:31
  def relevant_edges(graph); end
end

# Backs ArchSpec::DSL::ComponentProxy#cannot_use. Flags references from the
# source to any of the named components.
#
# pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:61
class ArchSpec::Rules::ForbidDependenciesRule < ::ArchSpec::Rules::DependencyRule
  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:66
  def evaluate(graph); end

  # pkg:gem/archspec#lib/archspec/rules/dependency_rules.rb:62
  def id; end
end

# Backs ArchSpec::DSL::ComponentProxy#must_be_empty. Flags every file in a
# component that is meant to hold none.
#
# pkg:gem/archspec#lib/archspec/rules/component_rules.rb:7
class ArchSpec::Rules::MustBeEmptyRule
  # pkg:gem/archspec#lib/archspec/rules/component_rules.rb:10
  def initialize(source); end

  # pkg:gem/archspec#lib/archspec/rules/component_rules.rb:22
  def evaluate(graph); end

  # pkg:gem/archspec#lib/archspec/rules/component_rules.rb:18
  def id; end

  # pkg:gem/archspec#lib/archspec/rules/component_rules.rb:14
  def merge_key; end

  # pkg:gem/archspec#lib/archspec/rules/component_rules.rb:8
  def source; end
end

# Backs ArchSpec::DSL::ComponentProxy#must_implement_one_of. Flags classes
# that implement none of the named methods.
#
# pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:182
class ArchSpec::Rules::MustImplementOneOfRule
  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:185
  def initialize(source, method_names, scope: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:208
  def evaluate(graph); end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:204
  def id; end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:199
  def merge!(other); end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:195
  def merge_key; end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:183
  def method_names; end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:183
  def scope; end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:183
  def source; end

  private

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:232
  def constants_for(graph); end
end

# Backs ArchSpec::DSL::ComponentProxy#must_implement. Flags classes in the
# component that do not implement the method, counting inherited and
# mixed-in methods.
#
# pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:85
class ArchSpec::Rules::MustImplementRule
  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:88
  def initialize(source, method_name, scope: T.unsafe(nil), arity: T.unsafe(nil), keywords: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:86
  def arity; end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:109
  def evaluate(graph); end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:105
  def id; end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:86
  def keywords; end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:101
  def merge_key; end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:86
  def method_name; end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:86
  def scope; end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:86
  def source; end

  private

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:127
  def constants_for(graph); end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:161
  def evidence_for(constant, definitions, implementations, unresolved); end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:150
  def method_label; end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:154
  def requirement_clause; end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:131
  def requirement_met?(implementations); end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:146
  def signature_known?(implementations); end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:142
  def signature_required?; end
end

# The selectors and constraints the naming DSL composes, plus the builder the
# DSL returns.
#
# pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:54
module ArchSpec::Rules::Naming; end

# Returned by ArchSpec::DSL::ComponentProxy#method_names. Starts a selector.
#
# pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:161
class ArchSpec::Rules::Naming::Builder
  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:162
  def initialize(component, scope: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:167
  def matching(regex); end
end

# Forbids any selected method from existing. Rule id +naming.forbidden+.
#
# pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:76
class ArchSpec::Rules::Naming::Forbidden
  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:81
  def diagnostics(selected, rule, _graph); end

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:77
  def id; end
end

# Selects methods whose name matches a regex. A named capture in the regex
# (such as <tt>(?<base>.+)</tt>) is exposed to the +requires+ constraint.
#
# pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:57
class ArchSpec::Rules::Naming::NameSelector
  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:60
  def initialize(regex); end

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:70
  def describe; end

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:66
  def match(definition); end

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:58
  def regex; end
end

# Requires each selected method to have a sibling named by a template, in
# the same component or another (+on:+), at a given scope. The template
# interpolates the selector's named captures, as in
# <tt>requires("without_%{base}")</tt>. Rule id +naming.requires+.
#
# pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:99
class ArchSpec::Rules::Naming::Requires
  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:100
  def initialize(template, on: T.unsafe(nil), scope: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:115
  def diagnostics(selected, rule, graph); end

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:111
  def id; end

  private

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:145
  def captures(match); end

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:134
  def existing_names(graph, target); end

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:139
  def expand(match); end

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:149
  def message_for(definition, sibling, target, rule); end
end

# A chosen selector, waiting for a constraint. Each constraint method builds
# a NamingRule, attaches it, and returns the component proxy so rules chain.
#
# pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:174
class ArchSpec::Rules::Naming::Selected
  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:175
  def initialize(component, selector, scope); end

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:181
  def forbidden(except: T.unsafe(nil), because: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:185
  def requires(template, on: T.unsafe(nil), scope: T.unsafe(nil), except: T.unsafe(nil), because: T.unsafe(nil)); end

  private

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:192
  def add(constraint, except, because); end

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:204
  def component_name(target); end

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:215
  def validate_template!(template); end
end

# Backs the +method_names.matching(...)+ DSL. One rule pairs a selector (which
# methods it judges) with a constraint (what must hold of them). It judges a
# component's defined, public methods in the requested scope, or every such
# method in the project when +source+ is nil. Every finding is name-based and
# exact, so confidence is always +:high+.
#
# pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:12
class ArchSpec::Rules::NamingRule
  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:17
  def initialize(source:, selector:, constraint:, scope: T.unsafe(nil), except: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:33
  def evaluate(graph); end

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:15
  def except; end

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:29
  def id; end

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:15
  def scope; end

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:15
  def selector; end

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:15
  def source; end

  private

  # pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:46
  def candidate_methods(graph); end
end

# pkg:gem/archspec#lib/archspec/rules/naming_rules.rb:13
ArchSpec::Rules::NamingRule::VALID_SCOPES = T.let(T.unsafe(nil), Array)

# Backs ArchSpec::DSL::Context#no_cycles. Flags each group of components
# that depend on each other, reporting the group once with an example cycle.
#
# pkg:gem/archspec#lib/archspec/rules/cycle_rule.rb:7
class ArchSpec::Rules::NoCyclesRule
  # pkg:gem/archspec#lib/archspec/rules/cycle_rule.rb:10
  def initialize(among: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/rules/cycle_rule.rb:8
  def components; end

  # One diagnostic per strongly connected component. Every component in an
  # SCC reaches every other one, so the group is the thing to break up;
  # enumerating its elementary cycles instead reports the same tangle
  # exponentially many times.
  #
  # pkg:gem/archspec#lib/archspec/rules/cycle_rule.rb:22
  def evaluate(graph); end

  # pkg:gem/archspec#lib/archspec/rules/cycle_rule.rb:14
  def id; end

  private

  # pkg:gem/archspec#lib/archspec/rules/cycle_rule.rb:65
  def adjacency_for(locations); end

  # pkg:gem/archspec#lib/archspec/rules/cycle_rule.rb:114
  def canonical_cycle(cycle); end

  # Every component pair with a dependency between them, mapped to the first
  # edge that creates it so a reported cycle can point at real source.
  #
  # pkg:gem/archspec#lib/archspec/rules/cycle_rule.rb:45
  def dependency_locations(graph); end

  # pkg:gem/archspec#lib/archspec/rules/cycle_rule.rb:108
  def message_for(group, cycle); end

  # pkg:gem/archspec#lib/archspec/rules/cycle_rule.rb:102
  def path_to(previous, start, node); end

  # The tightest loop in the group, as the first thing to break. Every
  # member is a valid starting point, so canonicalize before comparing to
  # keep the choice stable across runs.
  #
  # pkg:gem/archspec#lib/archspec/rules/cycle_rule.rb:74
  def shortest_cycle(adjacency, group); end

  # pkg:gem/archspec#lib/archspec/rules/cycle_rule.rb:83
  def shortest_cycle_through(adjacency, start, members); end
end

# Builds the shared "methods: ..." evidence string for the protocol rules
# and resolves the classes in a component. Internal helper.
#
# pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:239
module ArchSpec::Rules::ProtocolEvidence
  private

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:250
  def constants_for(graph, source); end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:257
  def for(constant, methods, unresolved, scope: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:244
  def validate_scope!(scope, for_rule:); end

  class << self
    # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:250
    def constants_for(graph, source); end

    # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:257
    def for(constant, methods, unresolved, scope: T.unsafe(nil)); end

    # pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:244
    def validate_scope!(scope, for_rule:); end
  end
end

# pkg:gem/archspec#lib/archspec/rules/protocol_rules.rb:242
ArchSpec::Rules::ProtocolEvidence::VALID_SCOPES = T.let(T.unsafe(nil), Array)

# Backs ArchSpec::DSL::ComponentProxy#public_api. Flags references from
# outside the component to constants that are not part of its public API.
#
# pkg:gem/archspec#lib/archspec/rules/privacy_rule.rb:7
class ArchSpec::Rules::PublicApiRule
  # pkg:gem/archspec#lib/archspec/rules/privacy_rule.rb:10
  def initialize(source, files: T.unsafe(nil), constants: T.unsafe(nil), namespaces: T.unsafe(nil)); end

  # pkg:gem/archspec#lib/archspec/rules/privacy_rule.rb:8
  def constants; end

  # pkg:gem/archspec#lib/archspec/rules/privacy_rule.rb:32
  def evaluate(graph); end

  # pkg:gem/archspec#lib/archspec/rules/privacy_rule.rb:8
  def file_patterns; end

  # pkg:gem/archspec#lib/archspec/rules/privacy_rule.rb:28
  def id; end

  # pkg:gem/archspec#lib/archspec/rules/privacy_rule.rb:21
  def merge!(other); end

  # pkg:gem/archspec#lib/archspec/rules/privacy_rule.rb:17
  def merge_key; end

  # pkg:gem/archspec#lib/archspec/rules/privacy_rule.rb:8
  def namespaces; end

  # pkg:gem/archspec#lib/archspec/rules/privacy_rule.rb:8
  def source; end

  private

  # pkg:gem/archspec#lib/archspec/rules/privacy_rule.rb:76
  def normalize_constant(value); end

  # Names from public files and constants: match exactly. Reopened
  # namespace modules land in public files too, so prefix matching there
  # would make the whole namespace public. Use namespace: for prefixes.
  #
  # pkg:gem/archspec#lib/archspec/rules/privacy_rule.rb:68
  def public?(name, public_names); end

  # pkg:gem/archspec#lib/archspec/rules/privacy_rule.rb:56
  def public_constant_names(graph); end
end

# Attaches a human reason to any rule without coupling that metadata to the
# rule's implementation or to diagnostic fingerprints.
#
# pkg:gem/archspec#lib/archspec/rules/reasoned.rb:7
module ArchSpec::Rules::Reasoned
  # pkg:gem/archspec#lib/archspec/rules/reasoned.rb:8
  def archspec_because; end

  # pkg:gem/archspec#lib/archspec/rules/reasoned.rb:10
  def archspec_because=(reason); end

  # pkg:gem/archspec#lib/archspec/rules/reasoned.rb:22
  def evaluate(graph); end
end

# Tarjan's algorithm: the components that mutually reach each other, in one
# pass over the graph.
#
# pkg:gem/archspec#lib/archspec/rules/cycle_rule.rb:124
class ArchSpec::Rules::StronglyConnectedComponents
  # pkg:gem/archspec#lib/archspec/rules/cycle_rule.rb:129
  def initialize(adjacency); end

  # pkg:gem/archspec#lib/archspec/rules/cycle_rule.rb:139
  def components; end

  private

  # pkg:gem/archspec#lib/archspec/rules/cycle_rule.rb:157
  def follow(node, target); end

  # pkg:gem/archspec#lib/archspec/rules/cycle_rule.rb:166
  def pop_component(root); end

  # pkg:gem/archspec#lib/archspec/rules/cycle_rule.rb:146
  def visit(node); end

  class << self
    # pkg:gem/archspec#lib/archspec/rules/cycle_rule.rb:125
    def of(adjacency); end
  end
end

# pkg:gem/archspec#lib/archspec/model.rb:60
class ArchSpec::SourceFile
  # pkg:gem/archspec#lib/archspec/model.rb:63
  def initialize(root:, path:, parse_errors:, suppressions:); end

  # pkg:gem/archspec#lib/archspec/model.rb:61
  def parse_errors; end

  # pkg:gem/archspec#lib/archspec/model.rb:61
  def path; end

  # pkg:gem/archspec#lib/archspec/model.rb:61
  def relative_path; end

  # pkg:gem/archspec#lib/archspec/model.rb:61
  def suppressions; end
end

# pkg:gem/archspec#lib/archspec/source_location.rb:6
class ArchSpec::SourceLocation < ::Data
  # pkg:gem/archspec#lib/archspec/source_location.rb:6
  def column; end

  # pkg:gem/archspec#lib/archspec/source_location.rb:6
  def end_column; end

  # pkg:gem/archspec#lib/archspec/source_location.rb:6
  def end_line; end

  # pkg:gem/archspec#lib/archspec/source_location.rb:6
  def line; end

  # pkg:gem/archspec#lib/archspec/source_location.rb:6
  def path; end

  # pkg:gem/archspec#lib/archspec/source_location.rb:17
  def relative_path(root); end

  class << self
    # pkg:gem/archspec#lib/archspec/source_location.rb:6
    def [](*_arg0); end

    # pkg:gem/archspec#lib/archspec/source_location.rb:7
    def from_prism(path, location); end

    # pkg:gem/archspec#lib/archspec/source_location.rb:6
    def inspect; end

    # pkg:gem/archspec#lib/archspec/source_location.rb:6
    def members; end

    # pkg:gem/archspec#lib/archspec/source_location.rb:6
    def new(*_arg0); end

    # pkg:gem/archspec#lib/archspec/source_location.rb:13
    def point(path, line, column); end
  end
end

# pkg:gem/archspec#lib/archspec/model.rb:52
class ArchSpec::Suppression < ::Data
  # pkg:gem/archspec#lib/archspec/model.rb:52
  def end_line; end

  # pkg:gem/archspec#lib/archspec/model.rb:53
  def matches?(diagnostic); end

  # pkg:gem/archspec#lib/archspec/model.rb:52
  def reason; end

  # pkg:gem/archspec#lib/archspec/model.rb:52
  def rule; end

  # pkg:gem/archspec#lib/archspec/model.rb:52
  def start_line; end

  class << self
    # pkg:gem/archspec#lib/archspec/model.rb:52
    def [](*_arg0); end

    # pkg:gem/archspec#lib/archspec/model.rb:52
    def inspect; end

    # pkg:gem/archspec#lib/archspec/model.rb:52
    def members; end

    # pkg:gem/archspec#lib/archspec/model.rb:52
    def new(*_arg0); end
  end
end

# A file of accepted existing violations. ArchSpec still checks the files
# these come from, but subtracts the recorded violations so you can adopt it
# in an existing app and burn the list down over time. Matched by
# ArchSpec::Diagnostic#fingerprint, so entries survive edits that shift lines.
#
# pkg:gem/archspec#lib/archspec/todo.rb:10
class ArchSpec::Todo
  # pkg:gem/archspec#lib/archspec/todo.rb:57
  def initialize(ids, root:); end

  # pkg:gem/archspec#lib/archspec/todo.rb:62
  def include?(diagnostic); end

  private

  # pkg:gem/archspec#lib/archspec/todo.rb:68
  def ids; end

  # pkg:gem/archspec#lib/archspec/todo.rb:68
  def root; end

  class << self
    # pkg:gem/archspec#lib/archspec/todo.rb:11
    def empty(root: T.unsafe(nil)); end

    # pkg:gem/archspec#lib/archspec/todo.rb:15
    def load(path, root:); end

    # pkg:gem/archspec#lib/archspec/todo.rb:39
    def write(path, diagnostics, root:); end
  end
end

# pkg:gem/archspec#lib/archspec/model.rb:143
ArchSpec::VERBS = T.let(T.unsafe(nil), Hash)

# pkg:gem/archspec#lib/archspec/version.rb:4
ArchSpec::VERSION = T.let(T.unsafe(nil), String)
