# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `capybara-playwright-driver` gem.
# Please instead update this file by running `bin/tapioca gem capybara-playwright-driver`.


# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/tmpdir_owner.rb:1
module Capybara; end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:188
module Capybara::CapybaraObscuredPatch
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:204
  def capybara_obscured?(x: T.unsafe(nil), y: T.unsafe(nil)); end
end

# ref: https://github.com/teamcapybara/capybara/blob/f7ab0b5cd5da86185816c2d5c30d58145fe654ed/lib/capybara/selenium/node.rb#L523
#
# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:190
Capybara::CapybaraObscuredPatch::OBSCURED_OR_OFFSET_SCRIPT = T.let(T.unsafe(nil), String)

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:2
module Capybara::ElementClickOptionPatch
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:3
  def perform_click_action(keys, **options); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:18
module Capybara::ElementDragToPatch
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:19
  def drag_to(target, **options); end
end

# ref: https://github.com/teamcapybara/capybara/pull/2424
#
# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:218
module Capybara::ElementDropPathCompatPatch
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:219
  def drop(*args); end
end

module Capybara::Node; end

class Capybara::Node::Base
  include ::Capybara::NodeActionsAllowLabelClickPatch
end

class Capybara::Node::Element < ::Capybara::Node::Base
  include ::Capybara::ElementClickOptionPatch
  include ::Capybara::ElementDragToPatch
  include ::Capybara::WithElementHandlePatch
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:49
module Capybara::NodeActionsAllowLabelClickPatch
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:146
  def check(locator = T.unsafe(nil), **options); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:142
  def choose(locator = T.unsafe(nil), **options); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:150
  def uncheck(locator = T.unsafe(nil), **options); end

  private

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:154
  def check_via_label_click(node_type, locator, checked:, allow_label_click: T.unsafe(nil), **options); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:170
  def should_use_label_click?(allow_label_click, options); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:50
class Capybara::NodeActionsAllowLabelClickPatch::SelectableElementHandler
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:51
  def initialize(node:, node_type:, locator:, checked:); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:58
  def set_checked_state_via_label?; end

  private

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:76
  def click_associated_label?(playwright_element_handle_or_locator); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:133
  def driver; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:87
  def find_playwright_element_handle_by_non_label_locator; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:109
  def non_label_playwright_element_handle_candidates(playwright_page); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:70
  def playwright_locator_by_label; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:126
  def scope_element; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:137
  def session_options; end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/tmpdir_owner.rb:2
module Capybara::Playwright; end

# Responsibility of this class is:
# - Handling Capybara::Driver commands.
# - Managing Playwright browser contexts and pages.
#
# Note that this class doesn't manage Playwright::Browser.
# We should not use Playwright::Browser#close in this class.
#
# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:12
class Capybara::Playwright::Browser
  include ::Capybara::Playwright::TmpdirOwner
  extend ::Forwardable

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:18
  def initialize(driver:, internal_logger:, playwright_browser:, page_options:, record_video: T.unsafe(nil), callback_on_save_trace: T.unsafe(nil), default_timeout: T.unsafe(nil), default_navigation_timeout: T.unsafe(nil)); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:390
  def accept_modal(dialog_type, **options, &block); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:210
  def active_element; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:58
  def clear_browser_contexts; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:330
  def close_window(handle); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:70
  def current_url; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:298
  def current_window_handle; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:396
  def dismiss_modal(dialog_type, **options, &block); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:194
  def evaluate_async_script(script, *args); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:187
  def evaluate_script(script, *args); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:180
  def execute_script(script, *args); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:126
  def find_css(query, **options); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:118
  def find_xpath(query, **options); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:381
  def fullscreen_window(handle); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:166
  def go_back; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:173
  def go_forward; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:146
  def html; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:371
  def maximize_window(handle); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:302
  def open_new_window(kind = T.unsafe(nil)); end

  # Not used by Capybara::Session.
  # Intended to be directly called by user.
  #
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:229
  def raw_screenshot(**options); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:96
  def refresh; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:346
  def resize_window_to(handle, width, height); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:134
  def response_headers; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:235
  def save_screenshot(path, **options); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:241
  def send_keys(*args); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:140
  def status_code; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:245
  def switch_to_frame(frame); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:322
  def switch_to_window(handle); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:160
  def title; end

  # Not used by Capybara::Session.
  # Intended to be directly called by user.
  #
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:221
  def video_path; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:76
  def visit(path); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:294
  def window_handles; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:340
  def window_size(handle); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:448
  def with_playwright_page(&block); end

  private

  # Capybara doesn't retry at this case since it doesn't use `synchronize { ... } for driver/browser methods.`
  # We have to retry ourselves.
  #
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:262
  def assert_page_alive(retry_count: T.unsafe(nil), &block); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:32
  def create_browser_context; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:48
  def create_page(browser_context); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:92
  def firefox?; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:313
  def on_window(handle, &block); end

  # Capybara follows Selenium's outer window size semantics.
  #
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:353
  def outer_window_size(page); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:290
  def pages; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:402
  def unwrap_node(args); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:357
  def viewport_size_for(page, width, height); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:412
  def wrap_node(arg); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser.rb:16
class Capybara::Playwright::Browser::NoSuchWindowError < ::StandardError; end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser_options.rb:3
class Capybara::Playwright::BrowserOptions
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser_options.rb:4
  def initialize(options); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser_options.rb:28
  def value; end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser_options.rb:8
Capybara::Playwright::BrowserOptions::LAUNCH_PARAMS = T.let(T.unsafe(nil), Array)

# playwright-ruby-client provides 3 methods to launch/connect browser.
#
# Playwright.create do |playwright|
#   playwright.chromium.launch do |browser|
#
# Playwright.connect_to_playwright_server do |playwright| ...
#   playwright.chromium.launch do |browser|
#
# Playwright.connect_to_browser_server do |browser| ...
#
# This class provides start/stop methods for driver.
# This is responsible for
# - managing PlaywrightExecution
# - launching browser with given option if needed
#
# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser_runner.rb:17
class Capybara::Playwright::BrowserRunner
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser_runner.rb:82
  def initialize(options); end

  # @return [::Playwright::Browser]
  #
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser_runner.rb:94
  def start; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser_runner.rb:99
  def stop; end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser_runner.rb:39
class Capybara::Playwright::BrowserRunner::PlaywrightConnectToBrowserServer
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser_runner.rb:40
  def initialize(endpoint_url, options); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser_runner.rb:54
  def playwright_browser; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser_runner.rb:49
  def playwright_execution; end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser_runner.rb:18
class Capybara::Playwright::BrowserRunner::PlaywrightConnectToPlaywrightServer
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser_runner.rb:19
  def initialize(endpoint_url, options); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser_runner.rb:32
  def playwright_browser; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser_runner.rb:28
  def playwright_execution; end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser_runner.rb:59
class Capybara::Playwright::BrowserRunner::PlaywrightCreate
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser_runner.rb:60
  def initialize(options); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser_runner.rb:75
  def playwright_browser; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/browser_runner.rb:69
  def playwright_execution; end
end

# LILO event handler
#
# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/dialog_event_handler.rb:6
class Capybara::Playwright::DialogEventHandler
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/dialog_event_handler.rb:20
  def initialize; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/dialog_event_handler.rb:27
  def add_handler(callable); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/dialog_event_handler.rb:25
  def default_handler=(_arg0); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/dialog_event_handler.rb:50
  def handle_dialog(dialog); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/dialog_event_handler.rb:35
  def remove_handler(id); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/dialog_event_handler.rb:41
  def with_handler(callable, &block); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/dialog_event_handler.rb:7
class Capybara::Playwright::DialogEventHandler::Item
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/dialog_event_handler.rb:8
  def initialize(dialog_proc); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/dialog_event_handler.rb:15
  def call(dialog); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/dialog_event_handler.rb:13
  def id; end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:5
class Capybara::Playwright::Driver < ::Capybara::Driver::Base
  include ::Capybara::Playwright::DriverExtension
  extend ::Forwardable

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:9
  def initialize(app, **options); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:147
  def accept_modal(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:135
  def active_element(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:143
  def close_window(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:120
  def current_url(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:138
  def current_window_handle(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:148
  def dismiss_modal(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:131
  def evaluate_async_script(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:130
  def evaluate_script(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:129
  def execute_script(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:124
  def find_css(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:123
  def find_xpath(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:142
  def fullscreen_window(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:127
  def go_back(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:128
  def go_forward(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:126
  def html(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:108
  def invalid_element_errors; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:141
  def maximize_window(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:25
  def needs_server?; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:115
  def no_such_window_error; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:145
  def open_new_window(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:122
  def refresh(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:84
  def reset!; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:140
  def resize_window_to(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:133
  def response_headers(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:132
  def save_screenshot(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:136
  def send_keys(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:134
  def status_code(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:137
  def switch_to_frame(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:146
  def switch_to_window(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:125
  def title(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:121
  def visit(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:24
  def wait?; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:144
  def window_handles(*, **, &); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:139
  def window_size(*, **, &); end

  private

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:27
  def browser; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:44
  def create_playwright_browser; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:57
  def default_logger; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:40
  def playwright_browser; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:78
  def quit; end
end

# Since existing user already monkey-patched Kernel#puts,
# (https://gist.github.com/searls/9caa12f66c45a72e379e7bfe4c48405b)
# Logger.new(STDOUT) should be avoided to use.
#
# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:68
class Capybara::Playwright::Driver::PutsLogger
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:69
  def info(message); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver.rb:73
  def warn(message); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver_extension.rb:3
module Capybara::Playwright::DriverExtension
  # Register screenshot save process.
  # The callback is called just before page is closed.
  # (just before #reset_session!)
  #
  # The **binary** (String) of the page screenshot is called back into the given block
  #
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver_extension.rb:9
  def on_save_raw_screenshot_before_reset(&block); end

  # Register screenrecord save process.
  # The callback is called just after page is closed.
  # (just after #reset_session!)
  #
  # The video path (String) is called back into the given block
  #
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver_extension.rb:26
  def on_save_screenrecord(&block); end

  # Register trace save process.
  # The callback is called just after trace is saved.
  #
  # The trace.zip path (String) is called back into the given block
  #
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver_extension.rb:42
  def on_save_trace(&block); end

  # Start Playwright tracing (doc: https://playwright.dev/docs/api/class-tracing#tracing-start)
  #
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver_extension.rb:53
  def start_tracing(name: T.unsafe(nil), screenshots: T.unsafe(nil), snapshots: T.unsafe(nil), sources: T.unsafe(nil), title: T.unsafe(nil)); end

  # Stop Playwright tracing (doc: https://playwright.dev/docs/api/class-tracing#tracing-stop)
  #
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver_extension.rb:63
  def stop_tracing(path: T.unsafe(nil)); end

  # Trace execution of the given block. The tracing is automatically stopped when the block is finished.
  #
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver_extension.rb:70
  def trace(name: T.unsafe(nil), screenshots: T.unsafe(nil), snapshots: T.unsafe(nil), sources: T.unsafe(nil), title: T.unsafe(nil), path: T.unsafe(nil), &block); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver_extension.rb:46
  def with_playwright_page(&block); end

  private

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver_extension.rb:34
  def callback_on_save_screenrecord(video_path); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver_extension.rb:30
  def callback_on_save_screenrecord?; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver_extension.rb:17
  def callback_on_save_screenshot(raw_screenshot); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/driver_extension.rb:13
  def callback_on_save_screenshot?; end
end

# Selector and checking methods are derived from twapole/apparition
# Action methods (click, select_option, ...) uses playwright.
#
# ref:
#   selenium:   https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selenium/node.rb
#   apparition: https://github.com/twalpole/apparition/blob/master/lib/capybara/apparition/node.rb
#
# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:238
class Capybara::Playwright::Node < ::Capybara::Driver::Node
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:239
  def initialize(driver, internal_logger, page, element); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1290
  def ==(other); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:330
  def [](name); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:298
  def all_text; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1190
  def checked?; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:645
  def click(keys = T.unsafe(nil), **options); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1202
  def disabled?; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:661
  def double_click(keys = T.unsafe(nil), **options); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:927
  def drag_to(target, **options); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1056
  def drop(*args); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1304
  def find_css(query, **options); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1296
  def find_xpath(query, **options); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:921
  def hover; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1286
  def inspect; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1218
  def multiple?; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1184
  def obscured?; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1234
  def path; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1214
  def readonly?; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1222
  def rect; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:652
  def right_click(keys = T.unsafe(nil), **options); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1067
  def scroll_by(x, y); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1082
  def scroll_to(element, location, position = T.unsafe(nil)); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:618
  def select_option; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1196
  def selected?; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:747
  def send_keys(*args); end

  # @param value [String, Array] Array is only allowed if node has 'multiple' attribute
  # @param options [Hash] Driver specific options for how to set a value on a node
  #
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:367
  def set(value, **options); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1275
  def shadow_root; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:359
  def style(styles); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1146
  def tag_name; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1271
  def trigger(event); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:631
  def unselect_option; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:345
  def value; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1150
  def visible?; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:309
  def visible_text; end

  protected

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:246
  def element; end

  private

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:250
  def assert_element_not_stale(&block); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:341
  def attribute(name); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:276
  def capybara_default_wait_time; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:641
  def parent_select_element; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:336
  def property(name); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1095
  def scroll_element_to_location(element, location); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1131
  def scroll_to_coords(x, y); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1117
  def scroll_to_location(location); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1024
Capybara::Playwright::Node::ATTACH_FILE = T.let(T.unsafe(nil), String)

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:422
class Capybara::Playwright::Node::Checkbox < ::Capybara::Playwright::Node::Settable
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:423
  def set(value, **options); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:668
class Capybara::Playwright::Node::ClickOptions
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:669
  def initialize(element, keys, options, default_timeout); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:686
  def as_params; end

  private

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:707
  def delay_ms; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:725
  def modifiers; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:733
  def position; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:695
  def timeout; end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:715
Capybara::Playwright::Node::ClickOptions::MODIFIERS = T.let(T.unsafe(nil), Hash)

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1035
Capybara::Playwright::Node::DROP_FILE = T.let(T.unsafe(nil), String)

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1046
Capybara::Playwright::Node::DROP_STRING = T.let(T.unsafe(nil), String)

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:574
class Capybara::Playwright::Node::DateInput < ::Capybara::Playwright::Node::Settable
  include ::Capybara::Playwright::Node::UpdateValueJS

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:577
  def set(value, **options); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:598
class Capybara::Playwright::Node::DateTimeInput < ::Capybara::Playwright::Node::Settable
  include ::Capybara::Playwright::Node::UpdateValueJS

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:601
  def set(value, **options); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:283
class Capybara::Playwright::Node::DragInterruptedError < ::StandardError; end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:935
class Capybara::Playwright::Node::DragTo
  # @param page [Playwright::Page]
  # @param source [Playwright::ElementHandle]
  # @param target [Playwright::ElementHandle]
  #
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:949
  def initialize(page, source, target, options, timeout); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:957
  def execute; end

  private

  # @param element [Playwright::ElementHandle]
  #
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:991
  def center_of(element); end

  # @returns Array<String>
  #
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1009
  def drop_modifiers; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1017
  def sleep_delay; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:997
  def with_key_pressing(keys); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:936
Capybara::Playwright::Node::DragTo::MODIFIERS = T.let(T.unsafe(nil), Hash)

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:285
class Capybara::Playwright::Node::ElementGeometry
  class << self
    # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:286
    def bounding_box(element); end
  end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:540
class Capybara::Playwright::Node::FileUpload < ::Capybara::Playwright::Node::Settable
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:541
  def set(value, **options); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:610
class Capybara::Playwright::Node::JSValueInput < ::Capybara::Playwright::Node::Settable
  include ::Capybara::Playwright::Node::UpdateValueJS

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:613
  def set(value, **options); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:282
class Capybara::Playwright::Node::MissingBoundingBoxError < ::StandardError; end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:280
class Capybara::Playwright::Node::NotActionableError < ::StandardError; end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:416
class Capybara::Playwright::Node::RadioButton < ::Capybara::Playwright::Node::Settable
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:417
  def set(_, **options); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:1111
Capybara::Playwright::Node::SCROLL_POSITIONS = T.let(T.unsafe(nil), Hash)

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:751
class Capybara::Playwright::Node::SendKeys
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:820
  def initialize(element_or_keyboard, keys); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:885
  def execute; end

  private

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:881
  def key_for(key); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:877
  def modifier_for(modifier); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:762
Capybara::Playwright::Node::SendKeys::KEYS = T.let(T.unsafe(nil), Hash)

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:752
Capybara::Playwright::Node::SendKeys::MODIFIERS = T.let(T.unsafe(nil), Hash)

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:891
class Capybara::Playwright::Node::SendKeys::PressKey
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:892
  def initialize(key:, modifiers:); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:905
  def execute_for(element); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:910
class Capybara::Playwright::Node::SendKeys::TypeText
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:911
  def initialize(text); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:915
  def execute_for(element); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:408
class Capybara::Playwright::Node::Settable
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:409
  def initialize(element, timeout, internal_logger); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:281
class Capybara::Playwright::Node::StaleReferenceError < ::StandardError; end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:432
class Capybara::Playwright::Node::TextInput < ::Capybara::Playwright::Node::Settable
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:433
  def set(value, **options); end

  private

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:534
  def ensure_attached; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:487
  def replace_text(keyboard, text); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:463
  def set_text(text, append:, keyboard:); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:513
  def type_lines(keyboard, parts); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:520
  def type_tab_separated_text(text, append:, keyboard:); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:504
  def type_text(keyboard, text); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:586
class Capybara::Playwright::Node::TimeInput < ::Capybara::Playwright::Node::Settable
  include ::Capybara::Playwright::Node::UpdateValueJS

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:589
  def set(value, **options); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:554
module Capybara::Playwright::Node::UpdateValueJS
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:555
  def update_value_js(element, value); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:5
module Capybara::Playwright::PageExtension
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:6
  def initialize(*args, **kwargs); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:91
  def capybara_accept_modal(dialog_type, **options, &block); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:186
  def capybara_current_frame; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:119
  def capybara_dismiss_modal(dialog_type, **options, &block); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:182
  def capybara_pop_frame; end

  # @param frame [Playwright::Frame]
  #
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:178
  def capybara_push_frame(frame); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:173
  def capybara_reset_frames; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:159
  def capybara_response_headers; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:145
  def capybara_set_last_response(response); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:169
  def capybara_status_code; end

  private

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:15
  def _update_internal_logger(internal_logger); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:40
  def capybara_dialog_event_handler; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:19
  def capybara_initialize; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:46
  def capybara_on_unexpected_modal(dialog); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:55
class Capybara::Playwright::PageExtension::DialogAcceptor
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:56
  def initialize(dialog_type, options); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:61
  def handle(dialog); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:70
class Capybara::Playwright::PageExtension::DialogMessageMatcher
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:71
  def initialize(text_or_regex_or_nil); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:79
  def matches?(message); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:151
class Capybara::Playwright::PageExtension::Headers < ::Hash
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page.rb:152
  def [](key); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page_options.rb:3
class Capybara::Playwright::PageOptions
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page_options.rb:4
  def initialize(options); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page_options.rb:38
  def value; end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/page_options.rb:8
Capybara::Playwright::PageOptions::NEW_PAGE_PARAMS = T.let(T.unsafe(nil), Array)

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/shadow_root_node.rb:5
class Capybara::Playwright::ShadowRootNode < ::Capybara::Playwright::Node
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/shadow_root_node.rb:6
  def initialize(driver, internal_logger, page, element); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/shadow_root_node.rb:11
  def all_text; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/shadow_root_node.rb:22
  def visible_text; end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/tmpdir_owner.rb:3
module Capybara::Playwright::TmpdirOwner
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/tmpdir_owner.rb:14
  def remove_tmpdir; end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/tmpdir_owner.rb:6
  def tmpdir; end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/tmpdir_owner.rb:22
class Capybara::Playwright::TmpdirOwner::TmpdirRemover
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/tmpdir_owner.rb:23
  def initialize(tmpdir); end

  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/tmpdir_owner.rb:28
  def call(*args); end
end

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/version.rb:5
Capybara::Playwright::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:36
module Capybara::WithElementHandlePatch
  # pkg:gem/capybara-playwright-driver#lib/capybara/playwright/node.rb:37
  def with_playwright_element_handle(&block); end
end

class Playwright::ElementHandle < ::Playwright::JSHandle
  include ::Capybara::CapybaraObscuredPatch
end

class Playwright::Page < ::Playwright::PlaywrightApi
  include ::Capybara::Playwright::PageExtension
end
