# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `image_hash` gem.
# Please instead update this file by running `bin/tapioca gem image_hash`.


# pkg:gem/image_hash#lib/image_hash/version.rb:1
class ImageHash
  # pkg:gem/image_hash#lib/image_hash.rb:5
  def initialize(path); end

  # pkg:gem/image_hash#lib/image_hash.rb:17
  def binary; end

  # pkg:gem/image_hash#lib/image_hash.rb:9
  def binary_hash; end

  # pkg:gem/image_hash#lib/image_hash.rb:13
  def hash; end

  private

  # pkg:gem/image_hash#lib/image_hash.rb:68
  def average_value; end

  # pkg:gem/image_hash#lib/image_hash.rb:54
  def desaturate; end

  # pkg:gem/image_hash#lib/image_hash.rb:58
  def image; end

  # pkg:gem/image_hash#lib/image_hash.rb:62
  def pixels; end

  # pkg:gem/image_hash#lib/image_hash.rb:72
  def rgb_to_value(r, g, b); end

  # pkg:gem/image_hash#lib/image_hash.rb:50
  def scale_down; end

  class << self
    # pkg:gem/image_hash#lib/image_hash.rb:36
    def binary_distance(s1, s2); end

    # pkg:gem/image_hash#lib/image_hash.rb:30
    def binary_to_hex(binary); end

    # pkg:gem/image_hash#lib/image_hash.rb:43
    def distance(s1, s2); end

    # pkg:gem/image_hash#lib/image_hash.rb:24
    def hex_to_binary(hex); end
  end
end

# pkg:gem/image_hash#lib/image_hash/version.rb:2
ImageHash::VERSION = T.let(T.unsafe(nil), String)
