# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `prometheus_exporter` gem.
# Please instead update this file by running `bin/tapioca gem prometheus_exporter`.


# pkg:gem/prometheus_exporter#lib/prometheus_exporter/version.rb:3
module PrometheusExporter
  class << self
    # pkg:gem/prometheus_exporter#lib/prometheus_exporter.rb:36
    def detect_json_serializer(preferred); end

    # pkg:gem/prometheus_exporter#lib/prometheus_exporter.rb:45
    def has_oj?; end

    # pkg:gem/prometheus_exporter#lib/prometheus_exporter.rb:25
    def hostname; end
  end
end

# pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:7
class PrometheusExporter::Client
  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:54
  def initialize(host: T.unsafe(nil), port: T.unsafe(nil), max_queue_size: T.unsafe(nil), thread_sleep: T.unsafe(nil), connect_timeout: T.unsafe(nil), json_serializer: T.unsafe(nil), custom_labels: T.unsafe(nil), logger: T.unsafe(nil), log_level: T.unsafe(nil), process_queue_once_and_stop: T.unsafe(nil), tls_ca_file: T.unsafe(nil), tls_cert_file: T.unsafe(nil), tls_key_file: T.unsafe(nil)); end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:104
  def custom_labels=(custom_labels); end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:114
  def find_registered_metric(name, type: T.unsafe(nil), help: T.unsafe(nil)); end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:52
  def logger; end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:148
  def process_queue; end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:108
  def register(type, name, help, opts = T.unsafe(nil)); end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:138
  def send(str); end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:124
  def send_json(obj); end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:166
  def stop(wait_timeout_seconds: T.unsafe(nil)); end

  private

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:271
  def build_ssl_context; end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:209
  def close_socket!; end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:224
  def close_socket_if_old!; end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:231
  def ensure_socket!; end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:185
  def ensure_worker_thread!; end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:267
  def use_ssl?; end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:281
  def wait_for_empty_queue_with_timeout(timeout_seconds); end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:178
  def worker_loop; end

  class << self
    # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:41
    def default; end

    # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:45
    def default=(client); end
  end
end

# pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:50
PrometheusExporter::Client::MAX_QUEUE_SIZE = T.let(T.unsafe(nil), Integer)

# pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:49
PrometheusExporter::Client::MAX_SOCKET_AGE = T.let(T.unsafe(nil), Integer)

# pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:8
class PrometheusExporter::Client::RemoteMetric
  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:11
  def initialize(name:, help:, type:, client:, opts: T.unsafe(nil)); end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:36
  def decrement(keys = T.unsafe(nil), value = T.unsafe(nil)); end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:9
  def help; end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:32
  def increment(keys = T.unsafe(nil), value = T.unsafe(nil)); end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:9
  def name; end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:28
  def observe(value = T.unsafe(nil), keys = T.unsafe(nil)); end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:19
  def standard_values(value, keys, prometheus_exporter_action = T.unsafe(nil)); end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:9
  def type; end
end

# pkg:gem/prometheus_exporter#lib/prometheus_exporter.rb:9
PrometheusExporter::DEFAULT_BIND_ADDRESS = T.let(T.unsafe(nil), String)

# pkg:gem/prometheus_exporter#lib/prometheus_exporter.rb:11
PrometheusExporter::DEFAULT_LABEL = T.let(T.unsafe(nil), Hash)

# per: https://github.com/prometheus/prometheus/wiki/Default-port-allocations
#
# pkg:gem/prometheus_exporter#lib/prometheus_exporter.rb:8
PrometheusExporter::DEFAULT_PORT = T.let(T.unsafe(nil), Integer)

# pkg:gem/prometheus_exporter#lib/prometheus_exporter.rb:10
PrometheusExporter::DEFAULT_PREFIX = T.let(T.unsafe(nil), String)

# pkg:gem/prometheus_exporter#lib/prometheus_exporter.rb:13
PrometheusExporter::DEFAULT_REALM = T.let(T.unsafe(nil), String)

# pkg:gem/prometheus_exporter#lib/prometheus_exporter.rb:12
PrometheusExporter::DEFAULT_TIMEOUT = T.let(T.unsafe(nil), Integer)

# collects stats from currently running process
# collects stats from GoodJob
# see https://samsaffron.com/archive/2017/10/18/fastest-way-to-profile-a-method-in-ruby
# collects stats from currently running process
# collects stats from puma
# collects stats from resque
#
# pkg:gem/prometheus_exporter#lib/prometheus_exporter/instrumentation/method_profiler.rb:4
module PrometheusExporter::Instrumentation; end

# pkg:gem/prometheus_exporter#lib/prometheus_exporter/instrumentation/method_profiler.rb:7
class PrometheusExporter::Instrumentation::MethodProfiler
  class << self
    # pkg:gem/prometheus_exporter#lib/prometheus_exporter/instrumentation/method_profiler.rb:29
    def clear; end

    # pkg:gem/prometheus_exporter#lib/prometheus_exporter/instrumentation/method_profiler.rb:43
    def define_methods_on_module(klass, methods, name); end

    # pkg:gem/prometheus_exporter#lib/prometheus_exporter/instrumentation/method_profiler.rb:8
    def patch(klass, methods, name, instrument:); end

    # pkg:gem/prometheus_exporter#lib/prometheus_exporter/instrumentation/method_profiler.rb:71
    def patch_using_alias_method(klass, methods, name); end

    # pkg:gem/prometheus_exporter#lib/prometheus_exporter/instrumentation/method_profiler.rb:65
    def patch_using_prepend(klass, methods, name); end

    # pkg:gem/prometheus_exporter#lib/prometheus_exporter/instrumentation/method_profiler.rb:24
    def start(transfer = T.unsafe(nil)); end

    # pkg:gem/prometheus_exporter#lib/prometheus_exporter/instrumentation/method_profiler.rb:33
    def stop; end

    # pkg:gem/prometheus_exporter#lib/prometheus_exporter/instrumentation/method_profiler.rb:18
    def transfer; end
  end
end

# pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:290
class PrometheusExporter::LocalClient < ::PrometheusExporter::Client
  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:293
  def initialize(collector:, json_serializer: T.unsafe(nil), custom_labels: T.unsafe(nil)); end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:291
  def collector; end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/client.rb:298
  def send(json); end
end

# pkg:gem/prometheus_exporter#lib/prometheus_exporter/middleware.rb:6
class PrometheusExporter::Middleware
  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/middleware.rb:9
  def initialize(app, config = T.unsafe(nil)); end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/middleware.rb:53
  def call(env); end

  # allows subclasses to add custom labels based on env
  #
  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/middleware.rb:93
  def custom_labels(env); end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/middleware.rb:76
  def default_labels(env, result); end

  private

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/middleware.rb:139
  def apply_redis_client_middleware!; end

  # measures the queue time (= time between receiving the request in downstream
  # load balancer and starting request in ruby process)
  #
  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/middleware.rb:101
  def measure_queue_time(env); end

  # determine queue start from well-known trace headers
  #
  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/middleware.rb:116
  def queue_start(env); end

  # need to use CLOCK_REALTIME, as nginx/apache write this also out as the unix timestamp
  #
  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/middleware.rb:111
  def request_start; end
end

# pkg:gem/prometheus_exporter#lib/prometheus_exporter/middleware.rb:7
PrometheusExporter::Middleware::MethodProfiler = PrometheusExporter::Instrumentation::MethodProfiler

# pkg:gem/prometheus_exporter#lib/prometheus_exporter/middleware.rb:135
module PrometheusExporter::Middleware::RedisInstrumenter
  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/middleware.rb:136
  def call(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/prometheus_exporter#lib/prometheus_exporter/middleware.rb:136
  def call_pipelined(*_arg0, **_arg1, &_arg2); end
end

# pkg:gem/prometheus_exporter#lib/prometheus_exporter.rb:15
class PrometheusExporter::OjCompat
  class << self
    # pkg:gem/prometheus_exporter#lib/prometheus_exporter.rb:20
    def dump(obj); end

    # pkg:gem/prometheus_exporter#lib/prometheus_exporter.rb:16
    def parse(obj); end
  end
end

# pkg:gem/prometheus_exporter#lib/prometheus_exporter/version.rb:4
PrometheusExporter::VERSION = T.let(T.unsafe(nil), String)
