# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AirGradient::MeasuresJob`.
# Please instead update this file by running `bin/tapioca dsl AirGradient::MeasuresJob`.


class AirGradient::MeasuresJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: AirGradient::MeasuresJob).void)
      ).returns(T.any(AirGradient::MeasuresJob, FalseClass))
    end
    def perform_later(&block); end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
