- match:
    dependency_name: "aws-sdk-s3"
    update_type: semver:minor
- match:
    dependency_name: "brakeman"
    update_type: semver:minor
- match:
    dependency_name: "standard"
    update_type: semver:patch
