# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GeneratedUrlHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl GeneratedUrlHelpersModule`.


module GeneratedUrlHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def api_current_ip_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_current_user_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_gallery_images_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_gallery_remote_video_downloads_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_inbox_images_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_webhooks_todoist_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_gallery_book_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_gallery_image_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_gallery_remote_video_download_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_gallery_tag_social_media_link_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_gallery_tag_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_gallery_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_ingredient_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_plant_plant_image_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_plant_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_recipe_group_recipe_ingredient_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_recipe_group_recipe_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_recipe_group_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_settings_api_token_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_shared_bill_bill_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_shared_bill_payee_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_shared_bill_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_todo_room_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_todo_task_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def edit_user_group_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def galleries_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_book_read_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_book_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_books_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_bulk_delete_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_bulk_tag_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_bulk_upload_tag_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_bulk_upload_tags_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_bulk_upload_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_image_book_images_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_image_recent_tags_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_image_tag_search_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_image_tag_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_image_tags_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_image_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_images_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_processing_images_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_remote_video_download_retries_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_remote_video_download_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_remote_video_downloads_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_tag_auto_add_tag_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_tag_auto_add_tags_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_tag_search_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_tag_social_media_link_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_tag_social_media_links_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_tag_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_tags_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def gallery_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def home_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def inbox_image_assignments_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def inbox_image_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def inbox_images_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ingredient_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def ingredients_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def invitation_acceptance_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def invitation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_gallery_book_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_gallery_bulk_upload_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_gallery_image_book_image_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_gallery_remote_video_download_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_gallery_tag_auto_add_tag_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_gallery_tag_social_media_link_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_gallery_tag_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_gallery_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_inbox_image_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_ingredient_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_plant_plant_image_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_plant_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_rails_conductor_inbound_email_source_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_rails_conductor_inbound_email_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_recipe_group_recipe_ingredient_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_recipe_group_recipe_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_recipe_group_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_session_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_settings_api_token_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_shared_bill_bill_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_shared_bill_payee_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_shared_bill_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_todo_room_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_todo_task_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def new_user_group_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def plant_key_image_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def plant_plant_image_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def plant_plant_images_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def plant_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def plants_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def preview_view_component_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def preview_view_components_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_representation_proxy_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_representation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_blob_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_incinerate_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_reroute_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_sources_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_email_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_conductor_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_direct_uploads_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_disk_service_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_health_check_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_notes_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_properties_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_routes_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mailers_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mailgun_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mandrill_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mandrill_inbound_health_check_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_postmark_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_relay_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_representation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_sendgrid_inbound_emails_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_service_blob_proxy_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_service_blob_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_storage_proxy_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_storage_redirect_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def recipe_group_recipe_ingredient_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def recipe_group_recipe_ingredients_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def recipe_group_recipe_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def recipe_group_recipes_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def recipe_group_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def recipe_groups_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def root_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def session_callback_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def session_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def settings_api_token_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def settings_api_tokens_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def shared_bill_bill_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def shared_bill_bills_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def shared_bill_payee_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def shared_bill_payees_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def shared_bill_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def shared_bills_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def todo_room_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def todo_rooms_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def todo_task_occurrence_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def todo_task_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def todo_tasks_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def todo_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_recede_historical_location_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_refresh_historical_location_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def turbo_resume_historical_location_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def update_rails_disk_service_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_group_invitation_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_group_invitations_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_group_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def user_groups_url(*args); end
end
