# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `TestJob`.
# Please instead update this file by running `bin/tapioca dsl TestJob`.


class TestJob
  class << self
    sig { params(block: T.nilable(T.proc.params(job: TestJob).void)).returns(T.any(TestJob, FalseClass)) }
    def perform_later(&block); end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
