# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserGroupInvitationMailer`.
# Please instead update this file by running `bin/tapioca dsl UserGroupInvitationMailer`.


class UserGroupInvitationMailer
  class << self
    sig { params(user_group_invitation: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def invitation(user_group_invitation); end
  end
end
