# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserSeedJob`.
# Please instead update this file by running `bin/tapioca dsl UserSeedJob`.


class UserSeedJob
  class << self
    sig do
      params(
        user: T.untyped,
        block: T.nilable(T.proc.params(job: UserSeedJob).void)
      ).returns(T.any(UserSeedJob, FalseClass))
    end
    def perform_later(user, &block); end

    sig { params(user: T.untyped).returns(T.untyped) }
    def perform_now(user); end
  end
end
