# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SolidCable::TrimJob`.
# Please instead update this file by running `bin/tapioca dsl SolidCable::TrimJob`.


class SolidCable::TrimJob
  class << self
    sig do
      params(
        trim_batch_size: T.untyped,
        block: T.nilable(T.proc.params(job: SolidCable::TrimJob).void)
      ).returns(T.any(SolidCable::TrimJob, FalseClass))
    end
    def perform_later(trim_batch_size: T.unsafe(nil), &block); end

    sig { params(trim_batch_size: T.untyped).returns(T.untyped) }
    def perform_now(trim_batch_size: T.unsafe(nil)); end
  end
end
