# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Todoist::RescheduleRollableTasksJob`.
# Please instead update this file by running `bin/tapioca dsl Todoist::RescheduleRollableTasksJob`.


class Todoist::RescheduleRollableTasksJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: Todoist::RescheduleRollableTasksJob).void)
      ).returns(T.any(Todoist::RescheduleRollableTasksJob, FalseClass))
    end
    def perform_later(&block); end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
