default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 10 # seconds; default 0.1
    - queues: [priority]
      threads: 1
      processes: 1
      polling_interval: 10 # seconds; default 0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
