default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        reschedule_rollable_tasks:
          class: "Todoist::RescheduleRollableTasksJob"
          schedule: "0 2 * * *"
  workers:
    - queues: "*"
      threads: 3
      processes: 1
      polling_interval: 10 # seconds; default 0.1

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
