# typed: true

# Generated by `bin/rake erb_call_sites:generate` from
# app/views/todo/tasks/index.html.erb. Do not edit by hand.

module ErbCallSites
  class TodoTasksIndex
    sig { void }
    def call
      # app/views/todo/tasks/index.html.erb:1
      HeaderComponent.new(title: "Tasks")
    end
  end
end
