# typed: true

# Generated by `bin/rake erb_call_sites:generate` from
# app/views/todo/tasks/show.html.erb. Do not edit by hand.

module ErbCallSites
  class TodoTasksShow
    sig { void }
    def call
      # app/views/todo/tasks/show.html.erb:1
      HeaderComponent.new(title: @task.name)
    end
  end
end
