# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Galleries::BackfillAutoTagsJob`.
# Please instead update this file by running `bin/tapioca dsl Galleries::BackfillAutoTagsJob`.


class Galleries::BackfillAutoTagsJob
  class << self
    sig do
      params(
        auto_add_tag: T.untyped,
        block: T.nilable(T.proc.params(job: Galleries::BackfillAutoTagsJob).void)
      ).returns(T.any(Galleries::BackfillAutoTagsJob, FalseClass))
    end
    def perform_later(auto_add_tag, &block); end

    sig { params(auto_add_tag: T.untyped).returns(T.untyped) }
    def perform_now(auto_add_tag); end
  end
end
