# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Galleries::ImageProcessingJob`.
# Please instead update this file by running `bin/tapioca dsl Galleries::ImageProcessingJob`.


class Galleries::ImageProcessingJob
  class << self
    sig do
      params(
        image: T.untyped,
        block: T.nilable(T.proc.params(job: Galleries::ImageProcessingJob).void)
      ).returns(T.any(Galleries::ImageProcessingJob, FalseClass))
    end
    def perform_later(image, &block); end

    sig { params(image: T.untyped).returns(T.untyped) }
    def perform_now(image); end
  end
end
