# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Galleries::PerceptualHashJob`.
# Please instead update this file by running `bin/tapioca dsl Galleries::PerceptualHashJob`.


class Galleries::PerceptualHashJob
  class << self
    sig do
      params(
        image: ::Galleries::Image,
        block: T.nilable(T.proc.params(job: Galleries::PerceptualHashJob).void)
      ).returns(T.any(Galleries::PerceptualHashJob, FalseClass))
    end
    def perform_later(image, &block); end

    sig { params(image: ::Galleries::Image).void }
    def perform_now(image); end
  end
end
