# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Galleries::RemoteVideoDownloadJob`.
# Please instead update this file by running `bin/tapioca dsl Galleries::RemoteVideoDownloadJob`.


class Galleries::RemoteVideoDownloadJob
  class << self
    sig do
      params(
        remote_video_download: T.untyped,
        block: T.nilable(T.proc.params(job: Galleries::RemoteVideoDownloadJob).void)
      ).returns(T.any(Galleries::RemoteVideoDownloadJob, FalseClass))
    end
    def perform_later(remote_video_download, &block); end

    sig { params(remote_video_download: T.untyped).returns(T.untyped) }
    def perform_now(remote_video_download); end
  end
end
