# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Galleries::TaggingNeededJob`.
# Please instead update this file by running `bin/tapioca dsl Galleries::TaggingNeededJob`.


class Galleries::TaggingNeededJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: Galleries::TaggingNeededJob).void)
      ).returns(T.any(Galleries::TaggingNeededJob, FalseClass))
    end
    def perform_later(&block); end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
