# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Todo::SyncTaskOccurrencesJob`.
# Please instead update this file by running `bin/tapioca dsl Todo::SyncTaskOccurrencesJob`.


class Todo::SyncTaskOccurrencesJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: Todo::SyncTaskOccurrencesJob).void)
      ).returns(T.any(Todo::SyncTaskOccurrencesJob, FalseClass))
    end
    def perform_later(&block); end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
