# typed: true

# Generated by `bin/rake erb_call_sites:generate` from
# app/views/todo/rooms/edit.html.erb. Do not edit by hand.

module ErbCallSites
  class TodoRoomsEdit
    sig { void }
    def call
      # app/views/todo/rooms/edit.html.erb:1
      HeaderComponent.new(title: "Edit")
    end
  end
end
