# typed: true

# Generated by `bin/rake erb_call_sites:generate` from
# app/views/todo/rooms/index.html.erb. Do not edit by hand.

module ErbCallSites
  class TodoRoomsIndex
    sig { void }
    def call
      # app/views/todo/rooms/index.html.erb:1
      HeaderComponent.new(title: "Rooms")
    end
  end
end
