# typed: true

# Generated by `bin/rake erb_call_sites:generate` from
# app/views/todo/rooms/new.html.erb. Do not edit by hand.

module ErbCallSites
  class TodoRoomsNew
    sig { void }
    def call
      # app/views/todo/rooms/new.html.erb:1
      HeaderComponent.new(title: "New Room")
    end
  end
end
