# typed: true

# Generated by `bin/rake erb_call_sites:generate` from
# app/views/todo/rooms/show.html.erb. Do not edit by hand.

module ErbCallSites
  class TodoRoomsShow
    sig { void }
    def call
      task = T.unsafe(nil)

      # app/views/todo/rooms/show.html.erb:1
      HeaderComponent.new(title: @room.name)

      # app/views/todo/rooms/show.html.erb:34
      Todo::TaskCardComponent.new(task: task, room: @room)
    end
  end
end
