# typed: true

# Generated by `bin/rake erb_call_sites:generate` from
# app/views/todo/rooms/_task_card.html.erb. Do not edit by hand.

module ErbCallSites
  class TodoRoomsTaskCard
    sig { void }
    def call
      room = T.unsafe(nil)
      task = T.unsafe(nil)

      # app/views/todo/rooms/_task_card.html.erb:1
      Todo::TaskCardComponent.new(task: task, room: room)
    end
  end
end
